Docker Compose 3.8
jhipster/generator-jhipster pull request #12438
Opened 2020-09-11 14:42 UTC by qmonmert

Fix #12428 

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2020-09-13 14:41 UTC, DanielFran requested changes
Since you are not using extends, should be deleted files:
- consul.yml.ejs
- jhipster-registry.yml.ejs
- kafka.yml.ejs
- keycloak.yml.ejs
- prometheus.yml.ejs
- traefik.yml.ejs ?

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/01-gateway/src/main/docker/app.yml
> +        image: mysql:5.7.18
Use constant: <%= DOCKER_MYSQL %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/02-mysql/src/main/docker/app.yml
> +        image: mysql:5.7.18
Use constant: <%= DOCKER_MYSQL %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/03-psql/src/main/docker/app.yml
> +        image: postgres:9.5.1
Use constant: <%= DOCKER_POSTGRESQL %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/03-psql/src/main/docker/app.yml
> +        image: elasticsearch:2.4.6
Use constant: <%= DOCKER_ELASTICSEARCH %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/04-mongo/src/main/docker/app.yml
> +        image: mongo:4.2.3
Use constant: <%= DOCKER_MONGODB %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/05-cassandra/src/main/docker/app.yml
>          image: cassandra:2.2.5
Use constant: <%= DOCKER_CASSANDRA %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/06-uaa/src/main/docker/app.yml
> +        image: mysql:5.7.18
Use constant: <%= DOCKER_MYSQL %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/07-mariadb/src/main/docker/app.yml
> +        image: mariadb:10.3.7
Use constant: <%= DOCKER_MARIADB %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/08-monolith/src/main/docker/app.yml
> +        image: mysql:5.7.18
Use constant: <%= DOCKER_MYSQL %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/09-kafka/src/main/docker/app.yml
> +        image: mysql:5.7.20
Use constant: <%= DOCKER_MYSQL %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/09-kafka/src/main/docker/app.yml
> +        image: confluentinc/cp-kafka:5.2.1
Use constant: <%= DOCKER_KAFKA %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/09-kafka/src/main/docker/app.yml
> +        image: confluentinc/cp-zookeeper:5.2.1
Use constant: <%= DOCKER_ZOOKEEPER %>

2020-09-13 14:41 UTC, DanielFran commented on test/templates/compose/11-mssql/src/main/docker/app.yml
> +        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
Use constant: <%= DOCKER_MSSQL %>

2020-09-14 11:52 UTC, pascalgrimaud commented
I'll review and test it manually, self assign

2020-09-14 11:53 UTC, qmonmert commented
@pascalgrimaud not finished yet

2020-09-14 14:39 UTC, qmonmert commented
> Since you are not using extends, should be deleted files:
> 
> * consul.yml.ejs
> * jhipster-registry.yml.ejs
> * kafka.yml.ejs
> * keycloak.yml.ejs
> * prometheus.yml.ejs
> * traefik.yml.ejs ?

@DanielFran done

2020-09-19 15:52 UTC, pascalgrimaud approved these changes

2020-09-19 15:54 UTC, pascalgrimaud commented
Just tested it, and everything works fine:

```
17:48:00 in tmp/20-microservices/compose took 2m 52s 
➜ dpss
NAMES                            IMAGE                               STATUS              PORTS
compose_invoice_1                invoice                             Up 2 minutes        5701/udp, 8082/tcp
compose_product_1                product                             Up 2 minutes        5701/udp, 8081/tcp
compose_jhipster-registry_1      jhipster/jhipster-registry:v6.3.0   Up 2 minutes        0.0.0.0:8761->8761/tcp
compose_store-postgresql_1       postgres:12.4                       Up 2 minutes        5432/tcp
compose_invoice-postgresql_1     postgres:12.4                       Up 2 minutes        5432/tcp
compose_store_1                  store                               Up 2 minutes        5701/udp, 0.0.0.0:8080->8080/tcp
compose_notification_1           notification                        Up 2 minutes        8083/tcp
compose_notification-mongodb_1   mongo:4.4.0                         Up 2 minutes        27017/tcp
compose_product-postgresql_1     postgres:12.4                       Up 2 minutes        5432/tcp
```

Then, there will be more tests with the JDL Daily Builds, tomorrow :)

2020-09-19 15:54 UTC, merged