Generate the application with the user locale by default.
jhipster/generator-jhipster pull request #12810
Opened 2020-10-21 15:56 UTC by mshima

Closes https://github.com/jhipster/generator-jhipster/issues/12809.

- try to set nativeLanguage to current locale
- defaults to en when environment variable CI is true

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2020-10-22 11:52 UTC, MathieuAA requested changes
So the user has to specify a language if the locale one isn't the right one? all the time?
I don't think it's a good idea...

2020-10-22 11:52 UTC, MathieuAA commented on test/jdl/jhipster/default-application-options.spec.js
> +            it('should set the languages option to empty', () => {
should not set

2020-10-22 11:58 UTC, mshima commented on test/jdl/jhipster/default-application-options.spec.js
> +            it('should set the languages option to empty', () => {
Empty array then.

2020-10-22 12:00 UTC, mshima commented
> So the user has to specify a language if the locale one isn't the right one? all the time?
> I don't think it's a good idea...

Why is better to set 'en' then guessing from user locale?

2020-10-22 12:25 UTC, mshima commented on test/jdl/jhipster/default-application-options.spec.js
> +            it('should set the languages option to empty', () => {
```suggestion
            it('should set the languages option to empty array', () => {
```

2020-10-22 12:25 UTC, mshima commented on test/jdl/jhipster/default-application-options.spec.js
> +                expect(options.languages).to.have.lengthOf(0);
```suggestion
                expect(options.languages).to.be.eql([]);
```

2020-10-23 08:00 UTC, MathieuAA commented
Unless the user explicitly asks for a language, getting it fro the OS's locale may not work: my locale's set to French, but my apps are always in English.

2020-10-23 23:49 UTC, mshima commented
@MathieuAA dropped user language.

2020-10-29 18:49 UTC, mshima commented
> Unless the user explicitly asks for a language, getting it fro the OS's locale may not work: my locale's set to French, but my apps are always in English.

You just need to set your apps native language and languages at jdl.

Having default to user locale should mainly influence at examples like `jhipster jdl bug-tracker`.

2020-11-08 09:00 UTC, MathieuAA approved these changes

2020-11-08 09:10 UTC, pascalgrimaud commented
I didn't follow closely what is done here, but in my opinion, the command `jhipster jdl bug-tracker.jh` should generate the same project, no matter the machine

If it's different because of local, we'll have a lot of difficulty to reproduce, to guess the locale of the user etc...

Just my opinion

2020-11-08 13:03 UTC, mshima commented
@pascalgrimaud I planning to merge this PR so we can change the generator to make `jhipster jdl bug-tracker.jh --native-language xx` generate only the native language.

> I didn't follow closely what is done here, but in my opinion, the command `jhipster jdl bug-tracker.jh` should generate the same project, no matter the machine
> 
> If it's different because of local, we'll have a lot of difficulty to reproduce, to guess the locale of the user etc...
> 
> Just my opinion

Your concern is valid I will think about this.
Can you repost your comment at https://github.com/jhipster/generator-jhipster/issues/12900?

2020-11-08 13:18 UTC, merged

2020-11-08 15:14 UTC, pascalgrimaud commented
fine @mshima : I'm commenting the other ticket