[angular] Update Angular README
jhipster/generator-jhipster pull request #12869
Opened 2020-10-27 21:22 UTC by wmarques

As requested in #10624 

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2020-10-27 21:42 UTC, DanielFran requested changes

2020-10-27 21:42 UTC, DanielFran commented on generators/common/templates/README.md.ejs
> +The service worker initialization code is disabled by default. To enable it, uncomment the following code in `src/main/webapp/app/app.module.ts`:
Change `src/main/webapp/app/app.module.ts` by `<%= CLIENT_MAIN_SRC_DIR %>webapp/app/app.module.ts`

2020-10-27 22:16 UTC, gmarziou reviewed
Do you think that the Leaflet example in "Managing Dependencies" paragraph could/should be rewritten using `ng add`?

2020-10-28 22:58 UTC, wmarques commented
@gmarziou I think it's better to keep it. Not all dependencies use Angular Schematics so let's keep the "standard" way, it's more generic IMO.

2020-10-29 10:17 UTC, gmarziou commented
@wmarques OK it makes sense. 

I will test it soon and review the README by comparison with the one generated by Angular CLI, maybe I'll propose minor changes.

2020-11-17 14:41 UTC, wmarques commented on generators/common/templates/README.md.ejs
> +The service worker initialization code is disabled by default. To enable it, uncomment the following code in `src/main/webapp/app/app.module.ts`:
Done, thanks ! :)

2020-11-17 14:42 UTC, wmarques commented
@gmarziou @DanielFran it should be ok, thanks for your comments! Let me know if you have any others

2020-11-17 16:58 UTC, DanielFran approved these changes
LGTM

2020-11-18 13:29 UTC, merged