Simplify Code AccountResource
jhipster/generator-jhipster pull request #12922
Opened 2020-10-31 18:55 UTC by MarlonLuan

---

Boolean method 'checkPasswordLength' is always inverted 
 Inspection info: Reports methods with a boolean return type, which are only used in a negated context

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2020-10-31 19:12 UTC, murdos requested changes

2020-10-31 19:12 UTC, murdos commented on generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
> +        if (user.isEmpty()) {
We're still supporting Java8, so we can't use this newer API

2020-10-31 19:12 UTC, murdos commented on generators/server/templates/src/main/java/package/web/rest/AccountResource.java.ejs
> +        if (checkPasswordLength(passwordChangeDto.getNewPassword())) {
I'm not convinced that inverting the meaning of `checkPasswordLength` is an improvement. 
Or propose a new meaningful name for this method as e.g. `isPasswordLengthInvalid`

2020-10-31 20:08 UTC, gmarziou commented
Please consider squashing your commits and git force pushing.

2020-11-21 15:57 UTC, DanielFran approved these changes
LGTM

2020-11-21 15:57 UTC, merged