use default eslint for vue instead of tslint
jhipster/generator-jhipster pull request #12972
Opened 2020-11-06 06:20 UTC by atomfrede

Basically moves the changes done already in https://github.com/jhipster/jhipster-vuejs/pull/601 to the main generator.

Updates some 3rd party dependencies which have no breaking changes.

updates #12764

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2020-11-06 14:19 UTC, DanielFran requested changes

2020-11-06 14:19 UTC, DanielFran commented on generators/client/templates/vue/package.json.ejs
> +    "@fortawesome/fontawesome-svg-core": "1.2.32",
@atomfrede Can you migrate some of the dependencies to package.json file so the updates can be managed by dependabot automatically?

2020-11-06 14:23 UTC, DanielFran commented
Closing/Reopening to launch only Vue tests and relaunch failing tests

2020-11-07 15:29 UTC, pascalgrimaud commented
Just tested and it works well. Congrats @atomfrede ! Dont forget to claim your bounty at https://github.com/jhipster/jhipster-vuejs/issues/597

@DanielFran : your comment can be done in another PR I think. Let's merge this

2020-11-07 15:29 UTC, merged

2020-11-09 07:47 UTC, atomfrede commented
Will have a look at the dependabot integration when upgrading e.g. the terser plugin and doing some preparations for vue3.