Migrate to webpack 5
jhipster/generator-jhipster pull request #13615
Opened 2021-01-19 21:11 UTC by mshima

Fixes https://github.com/jhipster/generator-jhipster/issues/12712

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-01-19 21:52 UTC, mraible commented
You're awesome, @mshima! 😃

2021-01-19 21:53 UTC, DanielFran requested changes

2021-01-19 21:53 UTC, DanielFran commented on generators/client/templates/react/package.json
> +    "path-browserify": "^1.0.1",
Used fixed version

2021-01-19 22:00 UTC, mshima commented on generators/client/templates/react/package.json
> +    "path-browserify": "^1.0.1",
```suggestion
    "path-browserify": "1.0.1",
```

2021-01-20 09:55 UTC, DanielFran approved these changes

2021-01-20 09:55 UTC, merged

2021-01-20 17:16 UTC, mshima commented
Angular howto added to https://github.com/jhipster/generator-jhipster/issues/13642#issuecomment-763798399.

2021-01-27 19:58 UTC, mshima commented
Bounty claimed https://opencollective.com/generator-jhipster/expenses/32632

2021-01-27 20:05 UTC, pascalgrimaud commented
@mshima : approved

2021-01-27 20:07 UTC, mshima commented
Thanks @pascalgrimaud