support okta with cypress tests
jhipster/generator-jhipster pull request #13611
Opened 2021-01-19 07:17 UTC by atomfrede

This PR uses https://pptr.dev/ to do a "real" login at the oauth provider instead of doing manual calls to the providers api.
To overwrite the username and password must use `export CYPRESS_E2E_PASSWORD=XYZ` and `export CYPRESS_E2E_USERNAME=XYZ` which can be accessed via `Cypress.env('E2E_USERNAME')` for example.

You can watch the login process by setting the `headless` parameter in `plugins/index.tx` to false.

closes #12686

---

Please make sure the below checklist is followed for Pull Requests.

-   [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [ ] Tests are added where necessary
-   [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
-   [ ] Documentation is added/updated where necessary
-   [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-01-19 07:26 UTC, pascalgrimaud commented
Good job @atomfrede 
With this, maybe I could add a daily builds, dedicated to Okta

2021-01-19 07:39 UTC, atomfrede commented
> Good job @atomfrede
> With this, maybe I could add a daily builds, dedicated to Okta

Using the okta cli I think that should be possible.

2021-01-19 07:48 UTC, atomfrede commented
Sorry forgot to change the expected files (again) :facepalm:

2021-01-19 09:09 UTC, DanielFran requested changes

2021-01-19 09:09 UTC, DanielFran commented on generators/client/templates/angular/package.json.ejs
> +    "puppeteer": "VERSION_MANAGED_BY_CLIENT_COMMON",
```suggestion
    <%_ if (authenticationType === 'oauth2') { _%>
    "puppeteer": "VERSION_MANAGED_BY_CLIENT_COMMON",
    <%_ } _%>
```

2021-01-19 09:09 UTC, DanielFran commented on generators/client/templates/react/package.json.ejs
> +    "puppeteer": "VERSION_MANAGED_BY_CLIENT_COMMON",
```suggestion
    <%_ if (authenticationType === 'oauth2') { _%>
    "puppeteer": "VERSION_MANAGED_BY_CLIENT_COMMON",
    <%_ } _%>
```

2021-01-19 09:09 UTC, DanielFran commented on generators/client/templates/vue/package.json.ejs
> +    "puppeteer": "VERSION_MANAGED_BY_CLIENT_COMMON",
```suggestion
    <%_ if (authenticationType === 'oauth2') { _%>
    "puppeteer": "VERSION_MANAGED_BY_CLIENT_COMMON",
    <%_ } _%>
```

2021-01-19 09:09 UTC, DanielFran commented on generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs
> +
```suggestion
<%_ if (authenticationType === 'oauth2') { _%>
```

2021-01-19 09:09 UTC, DanielFran commented on generators/cypress/templates/src/test/javascript/cypress/plugins/index.ts.ejs
> +  });
```suggestion
  });
<%_ } _%>
```

2021-01-19 09:39 UTC, atomfrede commented
Thanks @DanielFran! Will integrate it later today

2021-01-19 22:10 UTC, mshima commented
Add okta support is a must, but adding puppeteer increased cypress run from ~12 to ~20.
So I am against switching from api to puppeteer for keycloak since it's working great right now.

2021-01-19 22:14 UTC, atomfrede commented
Good point. I think we can improve by not logging out for each test case as loading and redirecting to keycloak and back to the app takes the most time when looking at puppeteer not in headless mode

2021-01-19 22:20 UTC, mraible commented
I'm curious to know why Keycloak can be implemented without Puppeteer. Both Keycloak and Okta just have endpoints to facilitate OAuth flows. Does Cypress have a special plugin that makes it work with Keycloak easier?

2021-01-19 22:23 UTC, atomfrede commented
> I'm curious to know why Keycloak can be implemented without Puppeteer. Both Keycloak and Okta just have endpoints to facilitate OAuth flows. Does Cypress have a special plugin that makes it work with Keycloak easier?

The endpoints are not exactly the same as far as I can tell, so its hard to do it for both as far as I can see,

2021-01-19 22:30 UTC, mshima commented
> I can tell, so its hard to do it for both as far as I can see,

I think it's not hard.
Once we know what server we are using, just use the correct endpoint.

There is a best practices for authentication https://github.com/cypress-io/cypress/issues/2435#issuecomment-418953198. I didn't watch yet.
We can consider using https://github.com/cypress-io/cypress/issues/8301 once is released for keeping session states stored.
Not sure the best way to implement this.

2021-01-19 22:32 UTC, mraible commented
We have the issuer as a property in our config. If you add `/.well-known/openid-configuration` to the issuer URI, it should have all the endpoint information. That could be one workaround for the different endpoints and should with any OIDC provider.

For example, Keycloak's issuer is `http://localhost:9080/auth/realms/jhipster`. If you start the Docker container and go to http://localhost:9080/auth/realms/jhipster/.well-known/openid-configuration, you'll get the following as a response.

```json
{
  "issuer": "http://localhost:9080/auth/realms/jhipster",
  "authorization_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth",
  "token_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token",
  "introspection_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token/introspect",
  "userinfo_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/userinfo",
  "end_session_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/logout",
  "jwks_uri": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/certs",
  "check_session_iframe": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/login-status-iframe.html",
  "grant_types_supported": [
    "authorization_code",
    "implicit",
    "refresh_token",
    "password",
    "client_credentials"
  ],
  "response_types_supported": [
    "code",
    "none",
    "id_token",
    "token",
    "id_token token",
    "code id_token",
    "code token",
    "code id_token token"
  ],
  "subject_types_supported": [
    "public",
    "pairwise"
  ],
  "id_token_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512"
  ],
  "id_token_encryption_alg_values_supported": [
    "RSA-OAEP",
    "RSA1_5"
  ],
  "id_token_encryption_enc_values_supported": [
    "A256GCM",
    "A192GCM",
    "A128GCM",
    "A128CBC-HS256",
    "A192CBC-HS384",
    "A256CBC-HS512"
  ],
  "userinfo_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512",
    "none"
  ],
  "request_object_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512",
    "none"
  ],
  "response_modes_supported": [
    "query",
    "fragment",
    "form_post"
  ],
  "registration_endpoint": "http://localhost:9080/auth/realms/jhipster/clients-registrations/openid-connect",
  "token_endpoint_auth_methods_supported": [
    "private_key_jwt",
    "client_secret_basic",
    "client_secret_post",
    "tls_client_auth",
    "client_secret_jwt"
  ],
  "token_endpoint_auth_signing_alg_values_supported": [
    "PS384",
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "PS256",
    "PS512",
    "RS512"
  ],
  "claims_supported": [
    "aud",
    "sub",
    "iss",
    "auth_time",
    "name",
    "given_name",
    "family_name",
    "preferred_username",
    "email",
    "acr"
  ],
  "claim_types_supported": [
    "normal"
  ],
  "claims_parameter_supported": false,
  "scopes_supported": [
    "openid",
    "address",
    "email",
    "jhipster",
    "microprofile-jwt",
    "offline_access",
    "phone",
    "profile",
    "roles",
    "web-origins"
  ],
  "request_parameter_supported": true,
  "request_uri_parameter_supported": true,
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ],
  "tls_client_certificate_bound_access_tokens": true
}
```

2021-01-19 22:37 UTC, atomfrede commented
> We have the issuer as a property in our config. If you add `/.well-known/openid-configuration` to the issuer URI, it should have all the endpoint information. That could be one workaround for the different endpoints and should with any OIDC provider.
> 
> For example, Keycloak's issuer is `http://localhost:9080/auth/realms/jhipster`. If you start the Docker container and go to http://localhost:9080/auth/realms/jhipster/.well-known/openid-configuration, you'll get the following as a response.
> 
> ```json
> {
>   "issuer": "http://localhost:9080/auth/realms/jhipster",
>   "authorization_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth",
>   "token_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token",
>   "introspection_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/token/introspect",
>   "userinfo_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/userinfo",
>   "end_session_endpoint": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/logout",
>   "jwks_uri": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/certs",
>   "check_session_iframe": "http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/login-status-iframe.html",
>   "grant_types_supported": [
>     "authorization_code",
>     "implicit",
>     "refresh_token",
>     "password",
>     "client_credentials"
>   ],
>   "response_types_supported": [
>     "code",
>     "none",
>     "id_token",
>     "token",
>     "id_token token",
>     "code id_token",
>     "code token",
>     "code id_token token"
>   ],
>   "subject_types_supported": [
>     "public",
>     "pairwise"
>   ],
>   "id_token_signing_alg_values_supported": [
>     "PS384",
>     "ES384",
>     "RS384",
>     "HS256",
>     "HS512",
>     "ES256",
>     "RS256",
>     "HS384",
>     "ES512",
>     "PS256",
>     "PS512",
>     "RS512"
>   ],
>   "id_token_encryption_alg_values_supported": [
>     "RSA-OAEP",
>     "RSA1_5"
>   ],
>   "id_token_encryption_enc_values_supported": [
>     "A256GCM",
>     "A192GCM",
>     "A128GCM",
>     "A128CBC-HS256",
>     "A192CBC-HS384",
>     "A256CBC-HS512"
>   ],
>   "userinfo_signing_alg_values_supported": [
>     "PS384",
>     "ES384",
>     "RS384",
>     "HS256",
>     "HS512",
>     "ES256",
>     "RS256",
>     "HS384",
>     "ES512",
>     "PS256",
>     "PS512",
>     "RS512",
>     "none"
>   ],
>   "request_object_signing_alg_values_supported": [
>     "PS384",
>     "ES384",
>     "RS384",
>     "HS256",
>     "HS512",
>     "ES256",
>     "RS256",
>     "HS384",
>     "ES512",
>     "PS256",
>     "PS512",
>     "RS512",
>     "none"
>   ],
>   "response_modes_supported": [
>     "query",
>     "fragment",
>     "form_post"
>   ],
>   "registration_endpoint": "http://localhost:9080/auth/realms/jhipster/clients-registrations/openid-connect",
>   "token_endpoint_auth_methods_supported": [
>     "private_key_jwt",
>     "client_secret_basic",
>     "client_secret_post",
>     "tls_client_auth",
>     "client_secret_jwt"
>   ],
>   "token_endpoint_auth_signing_alg_values_supported": [
>     "PS384",
>     "ES384",
>     "RS384",
>     "HS256",
>     "HS512",
>     "ES256",
>     "RS256",
>     "HS384",
>     "ES512",
>     "PS256",
>     "PS512",
>     "RS512"
>   ],
>   "claims_supported": [
>     "aud",
>     "sub",
>     "iss",
>     "auth_time",
>     "name",
>     "given_name",
>     "family_name",
>     "preferred_username",
>     "email",
>     "acr"
>   ],
>   "claim_types_supported": [
>     "normal"
>   ],
>   "claims_parameter_supported": false,
>   "scopes_supported": [
>     "openid",
>     "address",
>     "email",
>     "jhipster",
>     "microprofile-jwt",
>     "offline_access",
>     "phone",
>     "profile",
>     "roles",
>     "web-origins"
>   ],
>   "request_parameter_supported": true,
>   "request_uri_parameter_supported": true,
>   "code_challenge_methods_supported": [
>     "plain",
>     "S256"
>   ],
>   "tls_client_certificate_bound_access_tokens": true
> }
> ```

So for okta we can use `https://dev-XXX.okta.com/oauth2/default/.well-known/openid-configuration`. But again we must know when to use okta or keycloak I think.

2021-01-19 22:41 UTC, mraible commented
Yes, that is correct. For Protractor, the login form fields are named the same, so we didn't need to do anything special there. The error message is different though, so there is [some logic for that](https://github.com/jhipster/generator-jhipster/blob/main/generators/client/templates/angular/src/test/javascript/e2e/account/account.spec.ts.ejs#L69).

2021-01-19 22:47 UTC, mshima commented
> We have the issuer as a property in our config. If you add `/.well-known/openid-configuration` to the issuer URI, it should have all the endpoint information. That could be one workaround for the different endpoints and should with any OIDC provider.

That's useful.
Once you get that, it's possible to use those endpoints.

> So for okta we can use `https://dev-XXX.okta.com/oauth2/default/.well-known/openid-configuration`. But again we must know when to use okta or keycloak I think. Will try it.

For keycloak realm is got from https://github.com/jhipster/generator-jhipster/blob/ff54054055990360b0c94eee2cf873b77ab22e72/generators/cypress/templates/src/test/javascript/cypress/support/keycloak-oauth2.ts.ejs#L7.
But maybe we should click at login button and get the url login button redirects to, not sure it helps.

2021-01-19 22:50 UTC, mshima commented
> I can have another look doing it via api (I also thought should be easy as its oidc protocol)

@atomfrede you edited my answer 😃.

2021-01-19 22:52 UTC, mshima commented
@atomfrede https://github.com/jhipster/generator-jhipster/pull/13611#issuecomment-763183825 last edited by atomfrede

2021-01-19 22:53 UTC, atomfrede commented
Currently it works like this:

* "click" on the login button and intercept the redirect without following it
* extract realm data etc from the location header
* okta does another redirect and does not contain the same data in the redirect

So proposal, we do the same and check if the location is okta (or keycloak) and depending on that we retrieve the information either from keycloak or okta. 
With that information we can now do the same "im memory form" and post it to the oauth provider.

2021-01-19 22:53 UTC, atomfrede commented
> > I can have another look doing it via api (I also thought should be easy as its oidc protocol)
> 
> @atomfrede you edited my answer smiley.
> I started doubting my sanity.

Sorry for that :facepalm:

2021-01-19 22:54 UTC, mshima commented
No problem.

2021-01-19 23:01 UTC, mshima commented
> Currently it works like this:
> 
> * "click" on the login button and intercept the redirect without following it
> * extract realm data etc from the location header
> * okta does another redirect and does not contain the same data in the redirect
> 
> So proposal, we do the same and check if the location is okta (or keycloak) and depending on that we retrieve the information either from keycloak or okta.
> With that information we can now do the same "im memory form" and post it to the oauth provider.

Maybe the location header and `/.well-known/openid-configuration` are the only required info.

* "click" on the login button and intercept the redirect without following it
* extract realm data etc from the location header
* get oauth endpoints with the location header info and `/.well-known/openid-configuration`

2021-01-19 23:04 UTC, atomfrede commented
> > Currently it works like this:
> > 
> > * "click" on the login button and intercept the redirect without following it
> > * extract realm data etc from the location header
> > * okta does another redirect and does not contain the same data in the redirect
> > 
> > So proposal, we do the same and check if the location is okta (or keycloak) and depending on that we retrieve the information either from keycloak or okta.
> > With that information we can now do the same "im memory form" and post it to the oauth provider.
> 
> Maybe the location header and `/.well-known/openid-configuration` are the only required info.
> 
>     * "click" on the login button and intercept the redirect without following it
> 
>     * extract realm data etc from the location header
> 
>     * get oauth endpoints with the location header info and `/.well-known/openid-configuration`

Yes that should work I think we have the same thing in mind. Will try it tomorrow.

2021-01-20 05:56 UTC, atomfrede commented
Some good news, I have the keycloak part working without any hard coded url parts. Okta gives a bad request at the moment, going to figure out why. I guess something regarding the redirect uri

2021-01-20 06:43 UTC, atomfrede commented
@mraible I think we can't do the same as for keycloak. The keycloak response is plain html so we can do the trick and submit the form with javascript. As the okta login requires javascript we need a real browser to have access to the form. So maybe we need to do the puppeteer part for okta only (until cypress allows visiting different base urls). 

![image](https://user-images.githubusercontent.com/203401/105136898-baf2ec80-5af2-11eb-97c4-16a7ad375e4e.png)

2021-01-20 07:12 UTC, pascalgrimaud commented
@atomfrede : just a little warn from me, about Puppeteer. We used it in the past, when there was PhantomJS, but if I remember well, we encounter a lot of issues with this, specially with private CI, Docker environment, with Windows or something else.

So we need to be careful with Puppeteer

2021-01-20 07:17 UTC, pascalgrimaud commented
Here the ticket: https://github.com/jhipster/generator-jhipster/issues/6567

Maybe it has changed since 3 years but we need to be careful

2021-01-20 07:49 UTC, atomfrede commented
Thanks @pascalgrimaud for the hint. I think we are save here for the default configuration as this definitely won't use puppeteer. But we still need it for okta I think as we can't access the login form via ajax. Eventually we can remove it again and use cypress as the mentioned issue is on their roadmap at least.

2021-01-20 10:20 UTC, mshima commented
> As the okta login requires javascript we need a real browser to have access to the form.

Do we need the form?
The redirect returned from jhipster app when clicked the login button isn’t enough?
Passing realm url as env var isn’t a good workaround, while we can’t figure out how to automatize it?

2021-01-20 10:27 UTC, atomfrede commented
The realm url we have thats not the problem. The redirect from jhipster app is fine and contains all data. Need to check if we can use the authorize without a browser/form post (which is doing the login as far as I can tell).

2021-01-20 10:34 UTC, atomfrede commented
It looks like we need to first use https://developer.okta.com/docs/reference/api/authn/ to get a sessionToken and afterwards do the redirect to the login page with that token to init api based login flow instead of form based login. https://developer.okta.com/docs/reference/api/oidc/

2021-01-20 10:50 UTC, mshima commented
Not sure exactly how you implemented it but as far as I understand you switched to login using html form for keycloak, so:
- Using forms only work when using oauth server at localhost multiple domains was not catch by our normal CI builds, only applies to microservice tests see https://github.com/jhipster/generator-jhipster/issues/12665
- current implementation doesn't use form at all, it uses POST requests:
https://github.com/jhipster/generator-jhipster/blob/4dfc2fb547fe8ed5cda84084c381633060cbe81b/generators/cypress/templates/src/test/javascript/cypress/support/keycloak-oauth2.ts.ejs#L48-L56

2021-01-21 21:15 UTC, atomfrede commented
Thanks @mshima for the hint. I have changed it such that the implementation has not changed for keycloak. For okta the pupeteer approach is used. Keycloak uses the form to retrieve the correct url where to send the post request to. As the okta login page requires javascript we can't do it. 
We could use the [okta specific extension ](https://developer.okta.com/docs/reference/api/oidc/#parameter-details) with `sessionToken` (not tried yet) but I would rather not implement specific parts here.

https://github.com/jhipster/generator-jhipster/blob/4dfc2fb547fe8ed5cda84084c381633060cbe81b/generators/cypress/templates/src/test/javascript/cypress/support/keycloak-oauth2.ts.ejs#L42-L46

2021-01-21 22:10 UTC, mshima commented on generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
> +    if (isOkta) {
`isOkta` is missing?

2021-01-21 22:10 UTC, mshima commented on generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
> +    cy.keycloakLogin(oauth2Data, username, password);
`keycloakLogin` Is missing.
If possible to use `authenticationUrl` instead of getting from form action would be great.

2021-01-25 12:54 UTC, DanielFran requested changes

2021-01-25 12:54 UTC, DanielFran commented on generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
> +    cy.task('login', {baseUrl: Cypress.config().baseUrl, username: username, password: password}).then((cookies: Array<any>) => {
Identation

2021-01-25 12:54 UTC, DanielFran commented on generators/cypress/templates/src/test/javascript/cypress/support/oauth2.ts.ejs
> +    cy.clearCookies();
Identation

2021-01-26 09:27 UTC, DanielFran approved these changes

2021-01-26 13:09 UTC, mshima commented
@mraible do you want to test before merging?

2021-01-26 18:20 UTC, mraible commented
I tested it with the `webflux-mongodb` sample, modifying it to use OAuth first. 

I created the project and tried running `npm run e2e` tests with Keycloak. ✅

Then, I integrated it with Okta (`okta apps create jhipster`), exported my credentials, and tried again.

```
source .okta.env
./mvnw
# open a new terminal window
export E2E_USERNAME=xxx
export E2E_PASSWORD=yyy
npm run e2e
```

Nope, it doesn't work. I'm not following any docs on purpose because I expect it to work like Protractor does.

```
  Running:  administration/administration.spec.ts                                           (1 of 3)


  /admin
    /metrics
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
      (Attempt 1 of 3) should load the page
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
      (Attempt 2 of 3) should load the page
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
      1) "before each" hook for "should load the page"


  0 passing (2m)
  1 failing

  1) /admin
       /metrics
         "before each" hook for "should load the page":
     CypressError: `cy.task('login')` failed with the following error:

> Navigation timeout of 30000 ms exceeded

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `/admin`
      at http://localhost:8080/__cypress/runner/cypress_runner.js:159728:19
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:10609:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:8544:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:8601:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:8646:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:8722:18)
      at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:5316:12)
      at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:5309:9)
      at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:5325:5)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:5195:14)
  From Your Spec Code:
      at Context.eval (http://localhost:8080/__cypress/tests?p=src/test/javascript/cypress/support/index.ts:422:8)

  From Node.js Internals:
    TimeoutError: Navigation timeout of 30000 ms exceeded
        at /Users/mraible/dev/webflux-mongodb/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
```

2021-01-26 19:23 UTC, atomfrede commented
You need to use CYPRESS_E2E_USERNAME and CYPRESS_E2E_PASSWORD.

2021-01-26 19:51 UTC, mraible commented
@atomfrede I tried with the `CYPRESS_` prefix and it works!

```
    ✔  All specs passed!                        02:31       16       16        -        -        -

Execution time: 2 min. 47 s.
```

Is it possible to remove the `CYPRESS_` prefix or is that required?

With Keycloak, it's much faster.

```
Execution time: 1 min. 6 s.
```

I believe this is expected. Is it possible to remove this warning, or at least suppress it?

```
waitFor is deprecated and will be removed in a future release. See 
https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
```

2021-01-26 19:56 UTC, atomfrede commented
The `CYPRESS_` prefix is more or less convention, such that you can access the environment variable via `Cypress.env` which seems the "official" way to me, see https://docs.cypress.io/guides/guides/environment-variables.html#Setting.

The deprecation warning I didn't notice, but will have a look.

2021-01-26 19:59 UTC, atomfrede commented
Replaced with `waitForSelector`

2021-01-26 20:36 UTC, mraible commented
@atomfrede I tried with your `waitFor` change and it seems to slow things down quite a bit.

```
Execution time: 3 min. 45 s.
```

Previously, it was 2 min. 47 s.

Of course, these aren't exact comparisons so it could just be something on my machine.

I tried changing `npm run e2e` to headless.

```
"e2e": "npm run e2e:cypress:headless",
```

It doesn't help much.

```
Execution time: 3 min. 33 s.
```

2021-01-26 20:58 UTC, mraible approved these changes

2021-01-27 07:21 UTC, atomfrede commented
> @atomfrede I tried with your `waitFor` change and it seems to slow things down quite a bit.
> 
> ```
> Execution time: 3 min. 45 s.
> ```

From the documentation `waitFor` did  call  `waitForSelector` (when called with a string as first and only parameter) so I should be environment related.

2021-01-27 07:41 UTC, merged

2021-01-27 19:21 UTC, atomfrede commented
Bounty claimed https://opencollective.com/generator-jhipster/expenses/32631

2021-01-27 20:04 UTC, pascalgrimaud commented
@atomfrede : approved