replace spring-cloud-hystrix with spring-cloud-resilience4j
jhipster/generator-jhipster pull request #14045
Opened 2021-02-22 20:54 UTC by atomfrede

This PR is an incomplete approach to replace spring cloud hystrix with spring cloud resilience4j. Open things:

* Health indicator or not. By default health indicators are disabled, see [here for the reason](https://resilience4j.readme.io/docs/getting-started-3#health-endpoint).
* OpenFeign does not yet support webflux/reactive. We use it in the gateway (which is now reactive only) and for reactive microservices. [Spring suggest](https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#reactive-support) to use https://github.com/Playtika/feign-reactive until spring cloud can support it via open feign. What should we do?
* I have create a "reactive microservice sample" via `jhipster jdl reactive-ms` and at least everything seems to work well

updates #14031

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-03-05 13:37 UTC, DanielFran commented
@jhipster/developers Should we include it in v7?

2021-03-05 13:51 UTC, pascalgrimaud commented
@DanielFran : we could but not priority, as I think we can go without it and upgrade for v7.1, v7.2 etc...

2021-03-05 14:21 UTC, atomfrede commented
Yes no pressure to include it. It can be done later on.

2021-03-05 15:01 UTC, murdos commented
> 
> 
> @jhipster/developers Maybe we should include it in v7?

@DanielFran https://github.com/jhipster/generator-jhipster/issues/14031#issuecomment-784874414 😉

2021-04-23 11:55 UTC, Tcharl commented
Time to go for it?

2021-07-13 21:41 UTC, jdubois commented
I've wanted this for a long time, so I'm adding a bug bounty

2021-08-11 10:08 UTC, atomfrede commented
In my manual tests I could not find any regressions too. Main question from my point of view if we want to expose the metrics by default or not

2021-09-06 10:26 UTC, atomfrede commented
Should we include this in the next 7.2 release to gather more feedback? I would say we can merge it.

2021-09-06 13:54 UTC, jdubois commented
Yes this is super important! Is this done, do you need help?

2021-09-07 19:24 UTC, atomfrede commented
I will first rebase and do a manual test with one of our microservice jdls, but I don't think there is anything blocking.

2021-09-07 20:22 UTC, atomfrede commented
I have added feign reactive already. I suppose we need to update e.g. `OAuth2InterceptedFeignConfiguration` too to use/support reactive feign ([which are right now not created when reactive is selected](https://github.com/jhipster/generator-jhipster/blob/48a060a8d585757c7139f16b96b2afee5ac8bd05/generators/server/files.js#L687)), but I would consider this not part of this PR.

2021-09-07 20:31 UTC, DanielFran commented
@atomfrede better to add feign-reactor-bom to Bom project?

2021-09-07 20:32 UTC, atomfrede commented
Yes that would be great.

2021-09-08 07:29 UTC, DanielFran commented
@atomfrede Created PR in bom project

2021-09-08 11:02 UTC, DanielFran requested changes

2021-09-08 11:02 UTC, DanielFran commented on generators/server/templates/pom.xml.ejs
> +            <version>3.1.1</version>
```suggestion
```

2021-09-10 20:18 UTC, DanielFran approved these changes

2021-09-13 07:39 UTC, atomfrede commented
All :green_circle: let's merge this.

2021-09-13 08:04 UTC, merged

2021-09-13 08:58 UTC, atomfrede commented
Bounty claimed https://opencollective.com/generator-jhipster/expenses/49923