Filter out page/sort/size as field names
jhipster/generator-jhipster pull request #14202
Opened 2021-03-06 22:16 UTC by gzsombor

Fix #14199 

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-03-07 09:11 UTC, pascalgrimaud requested changes

2021-03-07 09:11 UTC, pascalgrimaud commented on jdl/validators/jdl-with-application-validator.js
> +          `Field name '${fieldName}'found in ${entityName} is a reserved keyword, as it is used by Spring for pagination in the URL.`
```suggestion
          `Field name '${fieldName}' found in ${entityName} is a reserved keyword, as it is used by Spring for pagination in the URL.`
```

2021-03-07 09:11 UTC, pascalgrimaud commented on jdl/validators/jdl-without-application-validator.js
> +          `Field name '${fieldName}'found in ${entityName} is a reserved keyword, as it is used by Spring for pagination in the URL.`
```suggestion
          `Field name '${fieldName}' found in ${entityName} is a reserved keyword, as it is used by Spring for pagination in the URL.`
```

2021-03-07 13:19 UTC, pascalgrimaud approved these changes

2021-03-07 13:19 UTC, merged

2021-03-07 13:19 UTC, pascalgrimaud commented
Thanks so much for your quick fix @gzsombor

2021-03-07 21:31 UTC, gzsombor commented
Thanks and welcome!

2021-03-07 22:12 UTC, pascalgrimaud commented
@gzsombor : don't forget your bounty :-)

2021-03-11 08:16 UTC, gzsombor commented
Thanks, bounty claimed: https://opencollective.com/generator-jhipster/expenses/35782 :smiley:

2021-03-11 08:20 UTC, pascalgrimaud commented
@gzsombor : approved !