Fail to get jwt token
jhipster/generator-jhipster pull request #14443
Opened 2021-03-24 16:51 UTC by hwqllang

- authenticationToken need parsed
- key name is wrong in localStorage

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-03-24 16:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/generator-jhipster?pullRequest=14443) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/generator-jhipster?pullRequest=14443) before we can accept your contribution.<br/><hr/>**Gitea** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/generator-jhipster?pullRequest=14443) it.</sub>

2021-03-26 17:23 UTC, mshima commented
@hwqllang thanks for your PR.
Can you sign the cla?

We need to check if `JSON.parse` is required for all 3 client frameworks.

2021-03-26 18:14 UTC, gmarziou commented
@hwqllang can you explain why token parsing is required in swagger-ui?

Personally, I don't understand it because next line is using it in header as bearer token so I would think that base64 encoding is expected.

2021-03-27 11:38 UTC, pascalgrimaud commented
I think there is indeed a bug in your current 7.0.0, but it needs to be confirmed:
- Angular / React: swagger broken
- Vue: swagger is fine

This PR seems to fix the issue for Angular and React, but it won't work for Vue.
So IMO, the issue comes from the way how the token is stored

2021-03-28 03:01 UTC, mshima requested changes
@pascalgrimaud the problem seems to be that ngx-webstorage stores it encoded.
At this page we use bare localStorage.
Not sure we can fix it another way.

2021-03-28 03:07 UTC, mshima commented
@hwqllang can you fix the user of the first commit?

2021-03-29 01:49 UTC, hwqllang commented
@mshima sorry for that, the user of the first commit is wrong, it is default user of my server, and I don't know how to fix it.

2021-03-30 03:04 UTC, merged

2021-03-30 03:05 UTC, mshima commented
@hwqllang thanks and congrats for your first contribution.

2021-03-30 03:06 UTC, mshima commented
Tested with angular/react and remember me enabled/disabled.

2021-03-30 04:44 UTC, pascalgrimaud commented
@hwqllang : it's an important bug so I added a bounty on this. Don't forget to claim it

2021-03-31 16:34 UTC, hwqllang commented
Bounty claimed - https://opencollective.com/generator-jhipster/expenses/37328

2021-03-31 16:37 UTC, pascalgrimaud commented
@hwqllang : approved and thanks for your fix