Adding code coverage
jhipster/generator-jhipster pull request #14465
Opened 2021-03-26 02:46 UTC by jidma

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) was updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-03-26 02:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/jhipster/generator-jhipster?pullRequest=14465) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/jhipster/generator-jhipster?pullRequest=14465) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/jhipster/generator-jhipster?pullRequest=14465) it.</sub>

2021-03-30 11:36 UTC, mshima requested changes
This PR is interesting and you did a great job.
We should make it more modular and simplify it.

2021-03-30 18:02 UTC, mshima requested changes

2021-03-30 18:02 UTC, mshima commented on generators/cypress/index.js
> +  get prompting() {
Move prompting between initializing and loading (execution order).

2021-03-30 20:43 UTC, jidma commented on generators/cypress/index.js
> +    if (this.jhipsterConfig.cypressCoverage !== undefined) {
Thank you!

2021-03-31 00:49 UTC, mshima requested changes

2021-03-31 00:49 UTC, mshima commented on generators/client/templates/angular/webpack/webpack.custom.js.ejs
> +          },
I just saw that istanbul-instrumenter-loader was archived and conflicts with webpack 5 https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/110, so no angular 12, react or vue.

This is good for a blueprint, not for inclusion at jhipster.
Can you switch to babel-loader with istanbul plugin?

```suggestion
          {
            loader: 'babel-loader',
            options: {
              plugins: ['istanbul'],
            },
          },
```

2021-03-31 00:49 UTC, mshima commented on generators/client/templates/common/package.json
> +    "istanbul-instrumenter-loader": "3.0.1",
```suggestion
    "babel-loader": "8.2.2",
    "babel-plugin-istanbul": "6.0.0",
```

2021-03-31 00:49 UTC, mshima commented on generators/cypress/index.js
> +            'istanbul-instrumenter-loader': this.configOptions.dependabotPackageJson.devDependencies['istanbul-instrumenter-loader'],
```suggestion
            'babel-loader': this.configOptions.dependabotPackageJson.devDependencies['babel-loader'],
            'babel-plugin-istanbul': this.configOptions.dependabotPackageJson.devDependencies['babel-plugin-istanbul'],
```

2021-03-31 00:49 UTC, mshima commented on generators/common/templates/README.md.ejs
> +    npm run e2e:cypress:coverage
```suggestion
    npm run e2e:cypress
```

2021-03-31 00:49 UTC, mshima commented on generators/common/templates/README.md.ejs
> +### Code Coverage
```suggestion
### E2E Webapp Code Coverage
```

2021-03-31 00:49 UTC, mshima commented on generators/common/templates/README.md.ejs
> +When using Cypress with AngularX, you can generate code coverage report by running your dev server with instrumented code:
```suggestion
When using Cypress, you can generate code coverage report by running your dev server with instrumented code:
```

2021-03-31 00:49 UTC, mshima commented on generators/common/templates/README.md.ejs
> +Start your backend (option `-P-webapp` to skip compiling the Angular Front):
```suggestion
Start your backend without compiling frontend:
```

2021-03-31 00:49 UTC, mshima commented on generators/common/templates/README.md.ejs
> +    ./mvnw -P-webapp
```suggestion
    npm run backend:start
```

2021-03-31 01:13 UTC, mshima commented on generators/cypress/index.js
> +          this.createStorage('angular.json').merge({projects: {[this_.kebabCase(this.baseName)]: {architect: {build:{configurations:{instrumenter:{}}}}}]}});
```suggestion
          this.createStorage('angular.json').setPath(`projects.${this._.kebabCase(this.baseName)}.architect.build.configurations.instrumenter`, {});
```

2021-03-31 15:17 UTC, jidma commented
@mshima thank once again you for your code review.

After adding and testing your commit, I can't seem to get the instrumented code:

    npm run webapp:instrumenter

    ./mvnw -P-webapp   (because I'm currently on windows and npm run backend:start doesn't work for some reason)

The code doesn't seem to be instrumented:

![image](https://user-images.githubusercontent.com/2295247/113168140-e9e4b780-9233-11eb-9f53-a9dbfd010e59.png)

I wanted to let you know first (am I missing something obvious?) before I investigate further later.

2021-03-31 15:36 UTC, mshima requested changes
The loader is inside `if (targetOptions.target === 'serve' || config.watch)` but target is `build`.

Rebase against main for webpack needle support.

2021-03-31 15:43 UTC, mshima commented on generators/cypress/index.js
> +    };
```suggestion
      async askForCypressCoverage() {
        if (
          this.options.existingProject ||
          this.jhipsterConfig.clientFramework !== constants.SUPPORTED_CLIENT_FRAMEWORKS.ANGULAR ||
          !this.jhipsterConfig.testFrameworks.includes(CYPRESS)
        ) {
          return;
        }
        const answers = await this.prompt({
          type: 'confirm',
          name: 'cypressCoverage',
          message: 'Would you like to generate code coverage for Cypress tests? [Experimental]',
          default: this.jhipsterConfig.cypressCoverage || false,
        });

        this.cypressCoverage = this.jhipsterConfig.cypressCoverage = answers.cypressCoverage;
      },
    };
```
Little cleanup.

2021-03-31 18:23 UTC, jidma commented
@mshima it's working now. Thanks!

2021-03-31 18:37 UTC, mshima commented on generators/generator-base.js
> +    }
Readd this and add the option to the app constructor. To be easier to enable.

2021-04-01 17:53 UTC, mshima approved these changes
LGTM.

@jidma can you add an option to generator/app/index.js please?
See https://github.com/jhipster/generator-jhipster/pull/14465#discussion_r605132750.

2021-04-01 17:53 UTC, mshima commented on generators/client/templates/common/package.json
> +    "@cypress/code-coverage": "3.9.2"
```suggestion
    "@cypress/code-coverage": "3.9.2",
    "babel-loader": "8.2.2",
    "babel-plugin-istanbul": "6.0.0",
    "cypress": "6.6.0",
    "nyc": "15.1.0",
    "puppeteer": "8.0.0"
```
Reorder and add nyc to print the report.

2021-04-01 17:53 UTC, mshima commented on generators/client/templates/common/package.json
>      "cypress": "6.6.0",
```suggestion
```
Reorder

2021-04-01 17:53 UTC, mshima commented on generators/cypress/index.js
> +            'webapp:instrumenter': 'ng build --configuration instrumenter',
```suggestion
            'clean-coverage': 'rimraf .nyc_output coverage',
            'pree2e:cypress:coverage': 'npm run clean coverage && npm run ci:server:await',
            'e2e:cypress:coverage': 'npm run e2e:cypress',
            'poste2e:cypress:coverage': 'nyc report',
            'prewebapp:instrumenter': 'npm run clean-www && npm run clean-coverage',
            'webapp:instrumenter': 'ng build --configuration instrumenter',
```
Add script to print report.

2021-04-01 17:53 UTC, mshima commented on generators/cypress/index.js
> +            '@cypress/code-coverage': this.configOptions.dependabotPackageJson.devDependencies['@cypress/code-coverage'],
```suggestion
            '@cypress/code-coverage': this.configOptions.dependabotPackageJson.devDependencies['@cypress/code-coverage'],
            'babel-loader': this.configOptions.dependabotPackageJson.devDependencies['babel-loader'],
            'babel-plugin-istanbul': this.configOptions.dependabotPackageJson.devDependencies['babel-plugin-istanbul'],
            'nyc': this.configOptions.dependabotPackageJson.devDependencies['nyc'],
```

2021-04-01 18:46 UTC, jidma commented on generators/generator-base.js
> +    }
I added the code back but no idea how to add it to the constructor. Will check further later tonight.

2021-04-01 19:04 UTC, mshima commented on generators/generator-base.js
> +    }
Like here https://github.com/jhipster/generator-jhipster/blob/d72f9852bb691b5ae505f8cbdb0595b08d6d990a/generators/app/index.js#L241

2021-04-02 23:26 UTC, merged

2021-04-02 23:27 UTC, mshima commented
@jidma congratulations on your first contribution.

2021-04-03 21:41 UTC, jidma commented
> @jidma congratulations on your first contribution.

thank you the support!

2022-01-06 10:59 UTC, marcolafranca commented
Hi,
thank you for your work.
I have a problem when I enable this generator in jhipster wizard.
Jhipster 7.5.0

![image](https://user-images.githubusercontent.com/29198466/148372166-c3cd31ec-992c-4b07-852b-2535b373a247.png)

`ERROR! Error parsing file src\test\javascript\cypress\plugins\index.ts: SyntaxError: ';' expected. (27:4)
  25 |       return launchOptions;
  26 |     }
> 27 |   });
     |    ^
  28 |
  29 |   on('task', {
  30 |     lighthouse: lighthouse((lighthouseReport) => {

At: 1: // ***********************************************************
2: // This example plugins/index.js can be used to load plugins
3: //
4: // You can change the location of this file or turn off loading
5: // the plugins file with the 'pluginsFile' configuration option.
6: //
7: // You can read more here:
8: // https://on.cypress.io/plugins-guide
9: // ***********************************************************
10:
11: // This function is called when a project is opened or re-opened (e.g. due to
12: // the project's config changing)
13: import fs = require('fs');
14: import { lighthouse, pa11y, prepareAudit } from 'cypress-audit';
15: import ReportGenerator = require('lighthouse/report/generator/report-generator');
16: /**
17:  * @type {Cypress.PluginConfig}
18:  */
19: module.exports = (on, config) => {
20:   // `on` is used to hook into various events Cypress emits
21: // `config` is the resolved Cypress config  on('before:browser:launch', (browser, launchOptions) => {
22:     prepareAudit(launchOptions);
23:     if (browser.name === 'chrome' && browser.isHeadless) {
24:       launchOptions.args.push('--disable-gpu');
25:       return launchOptions;
26:     }
27:   });
28:
29:   on('task', {
30:     lighthouse: lighthouse((lighthouseReport) => {
31:       !fs.existsSync('target/cypress') && fs.mkdirSync('target/cypress', { recursive: true });
32:       fs.writeFileSync('target/cypress/lhreport.html', ReportGenerator.generateReport(lighthouseReport.lhr, 'html'));
33:     }),
34:     pa11y: pa11y(),
35:   });
36:     require('@cypress/code-coverage/task')(on, config);
37:     return config;
38: }
39:
Error: Error parsing file src\test\javascript\cypress\plugins\index.ts: SyntaxError: ';' expected. (27:4)
  25 |       return launchOptions;
  26 |     }
> 27 |   });
     |    ^
  28 |
  29 |   on('task', {
  30 |     lighthouse: lighthouse((lighthouseReport) => {

At: 1: // ***********************************************************
2: // This example plugins/index.js can be used to load plugins
3: //
4: // You can change the location of this file or turn off loading
5: // the plugins file with the 'pluginsFile' configuration option.
6: //
7: // You can read more here:
8: // https://on.cypress.io/plugins-guide
9: // ***********************************************************
10:
11: // This function is called when a project is opened or re-opened (e.g. due to
12: // the project's config changing)
13: import fs = require('fs');
14: import { lighthouse, pa11y, prepareAudit } from 'cypress-audit';
15: import ReportGenerator = require('lighthouse/report/generator/report-generator');
16: /**
17:  * @type {Cypress.PluginConfig}
18:  */
19: module.exports = (on, config) => {
20:   // `on` is used to hook into various events Cypress emits
21: // `config` is the resolved Cypress config  on('before:browser:launch', (browser, launchOptions) => {
22:     prepareAudit(launchOptions);
23:     if (browser.name === 'chrome' && browser.isHeadless) {
24:       launchOptions.args.push('--disable-gpu');
25:       return launchOptions;
26:     }
27:   });
28:
29:   on('task', {
30:     lighthouse: lighthouse((lighthouseReport) => {
31:       !fs.existsSync('target/cypress') && fs.mkdirSync('target/cypress', { recursive: true });
32:       fs.writeFileSync('target/cypress/lhreport.html', ReportGenerator.generateReport(lighthouseReport.lhr, 'html'));
33:     }),
34:     pa11y: pa11y(),
35:   });
36:     require('@cypress/code-coverage/task')(on, config);
37:     return config;
38: }
39:
    at patternSpy.dot (C:\Users\marco_ye\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-transforms.js:79:15)
    at async PTransform.transform [as _transform] (C:\Users\marco_ye\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\p-transform\index.js:127:7)
    at async PTransform.queuedTransform (C:\Users\marco_ye\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\p-transform\index.js:88:26)
    at async run (C:\Users\marco_ye\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\p-queue\dist\index.js:163:29)
   create src\main\webapp\i18n\en\logs.json
   create src\test\javascript\cypress\fixtures\integration-test.png`

Can you help me? Thank you very much :-)