Fix Vue builds (temporarily)
jhipster/generator-jhipster pull request #15105
Opened 2021-05-25 12:18 UTC by qmonmert

All Vue builds failed currently, with this error:

`ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: No subdirectories found for mandatory directory location 'file:./config/*/'.`

I found a temporarily fix

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-05-25 13:09 UTC, mshima commented
Upstream bug: https://github.com/spring-projects/spring-boot/issues/26627

2021-05-25 13:10 UTC, qmonmert commented
> spring-projects/spring-boot#26627

@mshima yes I saw that

2021-05-25 13:11 UTC, mshima commented
Just for reference.

2021-05-25 13:24 UTC, qmonmert commented
@mshima I try

2021-05-25 13:30 UTC, qmonmert commented
@mshima it works :)

2021-05-25 13:30 UTC, DanielFran commented
@qmonmert @mshima Better to revert the upgrade to spring-boot 2.4.6?

2021-05-25 13:31 UTC, qmonmert commented
@DanielFran it works with Angular

2021-05-25 14:38 UTC, mshima commented
@qmonmert try renaming webpack/index.js to env.js.
Probably require('webpack') is conflicting.

2021-05-25 15:24 UTC, mshima approved these changes
Just missing cleanup at https://github.com/jhipster/generator-jhipster/blob/main/generators/cleanup.js

2021-05-25 16:51 UTC, DanielFran requested changes
@qmonmert I believe the path is not correct for the files you are removing

2021-05-25 16:51 UTC, DanielFran commented on generators/cleanup.js
> +      generator.removeFile('config/index.js');
```suggestion
      generator.removeFile('${VUE_DIR}config/index.js');
```

2021-05-25 16:51 UTC, DanielFran commented on generators/cleanup.js
> +      generator.removeFile('config/dev.env.js');
```suggestion
      generator.removeFile('${VUE_DIR}config/dev.env.js');
```

2021-05-25 16:51 UTC, DanielFran commented on generators/cleanup.js
> +      generator.removeFile('config/prod.env.js');
```suggestion
      generator.removeFile('${VUE_DIR}config/prod.env.js');
```

2021-05-25 16:59 UTC, qmonmert commented on generators/cleanup.js
> +      generator.removeFile('config/index.js');
ok :)

2021-05-25 16:59 UTC, qmonmert commented on generators/cleanup.js
> +      generator.removeFile('config/dev.env.js');
ok :)

2021-05-25 16:59 UTC, qmonmert commented on generators/cleanup.js
> +      generator.removeFile('config/prod.env.js');
ok :)

2021-05-25 17:06 UTC, mshima commented on generators/cleanup.js
> +      generator.removeFile('config/index.js');
I think it was correct

2021-05-25 19:43 UTC, mshima commented on generators/cleanup.js
> +      generator.removeFile('config/dev.env.js');
It's correct

2021-05-25 20:42 UTC, DanielFran approved these changes

2021-05-25 20:42 UTC, merged

2021-05-28 13:10 UTC, pascalgrimaud commented
Adding a bounty on this, for the time to investigate and fix the builds
Plz claim it, @qmonmert

2021-05-28 13:12 UTC, qmonmert commented
@pascalgrimaud https://opencollective.com/generator-jhipster/expenses/41624 :)

2021-05-28 13:14 UTC, pascalgrimaud commented
@qmonmert : approved