fix mssql and r2dbc integration
jhipster/generator-jhipster pull request #15264
Opened 2021-06-08 19:28 UTC by atomfrede

This PR fixes all issues mentioned in #15032 

* using `asEntity('User')` everywhere
* correcting the mssql r2dbc url
* adding the necessary setting to liquibase migration

closes #15032

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-06-09 09:17 UTC, DanielFran requested changes

2021-06-09 09:17 UTC, DanielFran commented on generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
> +            SET IDENTITY_INSERT jhi_user ON;
```suggestion
            SET IDENTITY_INSERT jhi_user OFF;
```

2021-06-09 09:22 UTC, atomfrede commented on generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
> +            SET IDENTITY_INSERT jhi_user ON;
:facepalm: You are right.

2021-06-09 10:02 UTC, DanielFran commented
@atomfrede @jhipster/developers We are using an explicit liquibase extension [sabomichal/liquibase-mssql](https://github.com/sabomichal/liquibase-mssql#change-loaddata) that allow defining the property _identityInsertEnabled="true"_ to _allows explicit values to be inserted into the identity column of a table_, so the same as defining "_SET IDENTITY_INSERT jhi_user ON/OFF_".
The use of this specific extension was due to no support for this MSSQL property in 2009: https://liquibase.jira.com/wiki/spaces/CONTRIB/pages/1998867/MS+SqlServer+Extensions

In the meantime, the support of official MSSQL is up-to-date, so we probably should migrate back to the [official liquibase extension](https://github.com/liquibase/liquibase-mssql).

So there are 2 possibilities:
1 - exclude the use of the property "[_identityInsertEnabled="true"_](https://github.com/jhipster/generator-jhipster/pull/15264/files#diff-ae745829fb5d7160e4baa8d1789c80a16a6f953f86aeec1720836a38b1d0d384R146)" explicitly for reactive and define "_SET IDENTITY_INSERT jhi_user ON/OFF_" only for reactive
2 - Drop use of sabomichal/liquibase-mssql in favour of the liquibase/liquibase-mssql and define "SET IDENTITY_INSERT jhi_user ON/OFF" like in the official extension for both reactive and non-reactive database

2021-06-09 10:06 UTC, DanielFran requested changes

2021-06-09 10:06 UTC, DanielFran commented on generators/server/templates/src/main/resources/config/liquibase/changelog/initial_schema.xml.ejs
> +            SET IDENTITY_INSERT jhi_user ON;
Needs review

2021-06-09 10:20 UTC, atomfrede commented
I would say let's use the official extension.

2021-06-09 10:59 UTC, atomfrede commented
But very strange it doesn't work with `identityInsertEnabled` property.

2021-06-09 11:47 UTC, DanielFran commented
Liquibase version we are using is version 4 and actually the extension was compatible with version 3, not sure there is any issue with the version4.

Anyway Liquibase should handle now reactive database also, so I agree the better is to switch with liquibase official extension.

2021-06-09 19:04 UTC, atomfrede commented
@DanielFran Done. Works fine (tested with reactive only though, but don't see why it should not work with classical jdbc).

2021-06-09 19:21 UTC, DanielFran commented
@atomfrede Can you please review tests?

2021-06-09 19:22 UTC, atomfrede commented
> @atomfrede Can you please review tests?

On it. Seems easy to fix.

2021-06-09 21:33 UTC, DanielFran approved these changes

2021-06-09 21:36 UTC, DanielFran commented
@atomfrede LGTM

Maybe we need to delete https://www.jhipster.tech/tips/004_tip_using_ms_sql_server.html

2021-06-09 21:36 UTC, merged

2021-06-10 07:42 UTC, atomfrede commented
Bounty claimed https://opencollective.com/generator-jhipster/expenses/42719.

Regarding the tip, there is already a disclaimer that the tip is not required anymore. But maybe it is time to delete it now.

2021-06-10 08:20 UTC, pascalgrimaud commented
@atomfrede : approved