Replace deprecated API for Kafka testcontainer
jhipster/generator-jhipster pull request #15602
Opened 2021-07-08 13:44 UTC by egvimo

Replace deprecated Java API for Kafka testcontainer and use the `DockerImageName` class.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-07-08 14:54 UTC, DanielFran requested changes
Better to use DOCKER_KAKFA constant: https://github.com/jhipster/generator-jhipster/blob/main/generators/generator-constants.js#L65

2021-07-08 14:54 UTC, DanielFran commented on generators/server/templates/src/test/java/package/web/rest/KafkaResourceIT.java.ejs
> +        kafkaContainer = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:<%= KAFKA_VERSION %>")).withNetwork(null);
```suggestion
        kafkaContainer = new KafkaContainer(DockerImageName.parse("<%= DOCKER_KAFKA %>")).withNetwork(null);
```

2021-07-08 17:07 UTC, DanielFran approved these changes
LGTM

2021-07-09 06:01 UTC, egvimo commented
I've pushed a clean commit (for a clean history). :)

2021-07-09 07:38 UTC, merged