Migrate to spring boot 2.5.2
jhipster/generator-jhipster pull request #15633
Opened 2021-07-12 14:04 UTC by jdubois

2021-07-13 15:41 UTC, jdubois commented on .github/actions/setup/action.yml
> +    default: https://github.com/jdubois/jhipster-bom.git
I need this to test at the moment, but I will revert it before merging, of course

2021-07-13 20:51 UTC, mshima commented on generators/server/index.js
> +          dockerAwaitScripts.push('echo "Waiting for Elasticsearch to start" && wait-on tcp:9200 && echo "Elasticsearch started"');
```suggestion
          dockerAwaitScripts.push('echo "Waiting for Elasticsearch to start" && wait-on "http-get://localhost:9200/_cluster/health?wait_for_status=green&timeout=60s" && echo "Elasticsearch started"');
```

2021-07-13 20:58 UTC, mshima commented on generators/entity-server/templates/src/main/java/package/repository/search/EntitySearchRepository.java.ejs
> +import org.springframework.data.domain.PageImpl;
```suggestion
  <%_ if (!reactive) { _%>
import java.util.List;
import java.util.stream.Collectors;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
  <%_ } _%>
```

2021-07-14 11:59 UTC, jdubois commented
It's all green, thank you @mshima !!!!

2021-07-14 12:42 UTC, DanielFran requested changes

2021-07-14 12:42 UTC, DanielFran commented on generators/server/templates/src/main/resources/config/application-dev.yml.ejs
> +  <%_ if (databaseType === 'mongodb' || databaseType === 'cassandra' || (searchEngine === 'elasticsearch' && reactive)) { _%>
With these changes, line 199 to 203 will never be filled.

2021-07-14 12:42 UTC, DanielFran commented on generators/server/templates/src/main/resources/config/application-dev.yml.ejs
> +  <%_ if (databaseType === 'mongodb' || databaseType === 'cassandra' || (searchEngine === 'elasticsearch' && reactive)) { _%>
```
    <%_ } else { _%>
   elasticsearch:
     rest:
       uris: http://localhost:9200
     <%_ } _%>
```

2021-07-14 12:50 UTC, DanielFran commented on generators/server/templates/src/main/resources/config/application-dev.yml.ejs
> +  <%_ if (databaseType === 'mongodb' || databaseType === 'cassandra' || (searchEngine === 'elasticsearch' && reactive)) { _%>
Mislead the condition, sorry ;)

2021-07-14 12:50 UTC, DanielFran approved these changes

2021-07-15 08:45 UTC, jdubois commented
@DanielFran I think this is failing because this is linked to https://github.com/jhipster/jhipster-bom/pull/372 - those PR where OK before migrating to the "jhipster" org, so I guess we can merge them both?

2021-07-15 09:42 UTC, merged

2021-07-15 10:06 UTC, jdubois commented
@DanielFran I forced the update of the new snapshot BOM on Maven Central, I hope it will help fix the build

2021-07-15 12:31 UTC, CGarces commented
Thanks! 

Now I can test liquibase 4.4.1
``` html
        <!-- The liquibase version should match the one managed by
        https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/${spring-boot.version} -->
        <liquibase.version>4.3.5</liquibase.version>
```