chore: Bump Keycloak dependency
jhipster/generator-jhipster pull request #15836
Opened 2021-08-03 19:08 UTC by vishal423

Closes #15783 
---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-08-04 19:35 UTC, vishal423 commented
There seems an issue with `jhipster-registry` after this upgrade resulting in test failures. I will try to spend sometime later this week to see if we can do something over here.

2021-08-14 18:19 UTC, vishal423 commented
The latest Keycloak `openid-configuration` endpoint response contains `mtls_endpoint_aliases`, that's not correctly parsed by `oauth2-oidc-sdk` dependency included in the last `JHipster-Registry` release. 

It seems the latest spring boot release `2.5.3` has the correct dependency and that's why it works fine in the new JHipster generated apps. Since `JHipster-Registry` relies on the generator BOM release, which in turn is synchronized with the JHipster release, we have to wait for the next JHipster release. Post that we should bump JHipster Registry to sync the dependencies, test and publish a new release, and then come back over here.

2021-09-10 17:31 UTC, DanielFran requested changes

2021-09-10 17:31 UTC, DanielFran commented on generators/docker-compose/templates/realm-config/jhipster-realm.json.ejs
> +  "keycloakVersion": "15.0.0",
```suggestion
  "keycloakVersion": "15.0.2",
```

2021-09-10 17:31 UTC, DanielFran commented on generators/generator-constants.js
> +const DOCKER_KEYCLOAK = 'jboss/keycloak:15.0.0'; // The version should match the attribute 'keycloakVersion' from /docker-compose/templates/realm-config/jhipster-realm.json.ejs and /server/templates/
```suggestion
const DOCKER_KEYCLOAK = 'jboss/keycloak:15.0.2'; // The version should match the attribute 'keycloakVersion' from /docker-compose/templates/realm-config/jhipster-realm.json.ejs and /server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs
```

2021-09-10 17:31 UTC, DanielFran commented on generators/server/templates/src/main/docker/config/realm-config/jhipster-realm.json.ejs
> +  "keycloakVersion": "15.0.0",
```suggestion
  "keycloakVersion": "15.0.2",
```

2021-09-11 15:55 UTC, pascalgrimaud commented
Ok I thought it was merged.
So, let's do it only for the next release 7.3.0 (instead of 7.2.0)

2021-09-22 18:41 UTC, danieljkemp commented
> Ok I thought it was merged.
> So, let's do it only for the next release 7.3.0 (instead of 7.2.0)

Is this still happening in 7.3.0?

2021-09-26 14:14 UTC, DanielFran commented
@vishal423 Can you finalize the Dev and sync with registry?

2021-09-26 15:39 UTC, vishal423 commented
> 
> 
> @vishal423 Can you finalize the Dev and sync with registry?

@DanielFran, we have to follow below steps:
- Check-in fix on registry ( there is a PR that unblocks this)
- Release registry
- Update registry dependency over here and re-run the PR tests.

2021-09-26 16:16 UTC, mshima commented
@vishal423 there is no need to release.
With https://github.com/jhipster/jhipster-registry/pull/514, we can use snapshot docker image.

2021-09-27 17:39 UTC, vishal423 commented
I see all tests passing (ignoring npm snapshot failures as they are due to temporary change to point to jhipster-registry snapshot). @pascalgrimaud , once you release the next jhipster-registry version, and update in generator, we can merge this PR.

I will revert temporary snapshot changes from this branch

2021-09-27 17:44 UTC, vishal423 commented
> 
> 
> I see all tests passing (ignoring npm snapshot failures as they are due to temporary change to point to jhipster-registry snapshot). @pascalgrimaud , once you release the next jhipster-registry version, and update in generator, we can merge this PR.
> 
> I will revert temporary snapshot changes from this branch

Or if we want to have snapshot integrated in generator and later change to released version, then, I can update jest snapshot tests to pass so that we can merge this PR as is

2021-09-27 17:50 UTC, mshima commented
+1 to use the snapshot.
I will try to sync jhipster-registry with main and improve sync process for next releases.

2021-09-28 07:27 UTC, DanielFran approved these changes

2021-09-30 15:12 UTC, vishal423 commented
Are we good over here?

2021-09-30 15:13 UTC, merged

2022-01-12 15:22 UTC, vishal423 commented
@pascalgrimaud bounty claimed @ https://opencollective.com/generator-jhipster/expenses/61026

2022-01-12 15:23 UTC, pascalgrimaud commented
@vishal423 : approved