Constantref
jhipster/generator-jhipster pull request #15966
Opened 2021-08-13 20:09 UTC by Tcharl

closes #14235 : You know what? I'm haaaaaappy :-)

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-08-13 21:27 UTC, DanielFran requested changes

2021-08-13 21:27 UTC, DanielFran commented on test/cypress.spec.js
> +    const options = { testFrameworks: ['cypress'], clientFramework: REACT, authenticationType: OAUTH2 };
```suggestion
    const options = { testFrameworks: [CYPRESS], clientFramework: REACT, authenticationType: OAUTH2 };
```

2021-08-13 21:27 UTC, DanielFran commented on test/cypress.spec.js
> +    const options = { testFrameworks: ['cypress'], clientFramework: ANGULAR_X, authenticationType: JWT };
```suggestion
    const options = { testFrameworks: [CYPRESS], clientFramework: ANGULAR_X, authenticationType: JWT };
```

2021-08-13 21:27 UTC, DanielFran commented on test/cypress.spec.js
> +    const options = { testFrameworks: ['cypress'], clientFramework: ANGULAR_X, authenticationType: OAUTH2 };
```suggestion
    const options = { testFrameworks: [CYPRESS], clientFramework: ANGULAR_X, authenticationType: OAUTH2 };
```

2021-08-14 10:17 UTC, Tcharl commented
Thank you Daniel!

2021-08-14 14:42 UTC, Tcharl commented
Are you okl with this one @DanielFran ?

2021-08-14 15:44 UTC, DanielFran approved these changes

2021-08-14 15:44 UTC, merged