authority check in SecurityUtils support array parameter
jhipster/generator-jhipster pull request #16192
Opened 2021-09-07 10:23 UTC by iconben

To provide some handy methods in scenario:   
- want to check if a user has any authority in a list of authorities
- want to check if a user has none of a list of authorities

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [x] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (bellow reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-09-08 04:39 UTC, iconben commented
Hi @mshima, I saw some checks failed due to network error, what should I do?

The error:
```
Could not download Saxon-HE-9.9.1-7.jar (net.sf.saxon:Saxon-HE:9.9.1-7)
      > Could not get resource 'https://plugins.gradle.org/m2/net/sf/saxon/Saxon-HE/9.9.1-7/Saxon-HE-9.9.1-7.jar'.
```

2021-09-08 16:59 UTC, vishal423 commented
Since these are utility methods and are currently not used anywhere in code, I suggest moving this to server-side library code in  https://github.com/jhipster/jhipster-bom project.

2021-09-09 01:24 UTC, iconben commented
> Since these are utility methods and are currently not used anywhere in code, I suggest moving this to server-side library code in https://github.com/jhipster/jhipster-bom project.

Should we merge this first, then discuss whether the whole SecurityUtils class should be moved to jhipster-bom ?

2021-09-09 04:34 UTC, vishal423 commented
I will rather close this PR as it would be surplus code for applications. JHipster server-side library is the perfect place to add these utility methods. Also, don't forget to add appropriate Junit tests.

2021-09-09 04:48 UTC, pascalgrimaud commented
Not sure about that @vishal423 

The current SecurityUtils is already generated by generator-jhipster and is used to check this kind of thing.
For my current customer, I added some specific method like this one, because the generated one is not enough.

So the good place is here. Anyway, this will add some dead code as it won't be used any where. Am I correct @iconben ?

2021-09-10 08:20 UTC, iconben commented
> Not sure about that @vishal423 
> 
> The current SecurityUtils is already generated by generator-jhipster and is used to check this kind of thing.
> For my current customer, I added some specific method like this one, because the generated one is not enough.
> 
> So the good place is here. Anyway, this will add some dead code as it won't be used any where. Am I correct @iconben ?

Yes and no, I added tests as well so they are used... in tests.😀

2021-09-10 10:37 UTC, mshima commented
IMO just point `hasCurrentUserThisAuthority` to `hasCurrentUserAnyOfAuthorities`.

While `hasCurrentUserNoneOfAuthorities` can be replaced with `!hasCurrentUserAnyOfAuthorities`.

The 3 implementations can reuse a single one.

2021-09-10 13:52 UTC, DanielFran requested changes

2021-09-10 13:52 UTC, DanielFran commented on generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs
> +    public static <% if (!reactive) { %>boolean<% } else { %>Mono<Boolean><% } %>  hasCurrentUserAnyOfAuthorities(String... authorities) {
```suggestion
    public static <% if (!reactive) { %>boolean<% } else { %>Mono<Boolean><% } %> hasCurrentUserAnyOfAuthorities(String... authorities) {
```

2021-09-10 13:52 UTC, DanielFran commented on generators/server/templates/src/main/java/package/security/SecurityUtils.java.ejs
> +    public static <% if (!reactive) { %>boolean<% } else { %>Mono<Boolean><% } %>  hasCurrentUserNoneOfAuthorities(String... authorities) {
```suggestion
    public static <% if (!reactive) { %>boolean<% } else { %>Mono<Boolean><% } %> hasCurrentUserNoneOfAuthorities(String... authorities) {
```

2021-09-10 20:32 UTC, DanielFran approved these changes

2021-09-10 20:32 UTC, merged

2021-09-10 20:33 UTC, DanielFran commented
Thanks @iconben for the contribution