[Angular] Tests: delete 'describe' useless
jhipster/generator-jhipster pull request #16392
Opened 2021-09-21 18:43 UTC by qmonmert

Some **describe** are useless

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2021-09-21 20:00 UTC, mshima approved these changes
Great.

2021-09-21 20:05 UTC, mshima requested changes
Oops, at entity service, the EJS ident should be reverted.

2021-09-21 20:05 UTC, mshima commented on generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> +<%_ } _%>
EJS ident should be kept

2021-09-21 20:05 UTC, mshima commented on generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> +<%_ } _%>
EJS ident should be kept.

2021-09-21 20:05 UTC, mshima commented on generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> +<%_ } _%>
EJS ident.

2021-09-21 20:05 UTC, mshima commented on generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> +<%_ } _%>
EJS ident.

2021-09-22 08:45 UTC, qmonmert commented
@mshima done

2021-09-22 12:05 UTC, mshima reviewed
A few more places to adjust ejs ident.

2021-09-22 12:05 UTC, mshima commented on generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> +const fieldType = field.fieldType;
ejs ident

2021-09-23 18:27 UTC, qmonmert commented
@mshima done :)

2021-09-23 21:34 UTC, mshima approved these changes
3 minor adjusts.
And we are ready to merge.

2021-09-23 21:34 UTC, mshima commented on generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> +    <%_ } _%>
```suggestion
<%_ } _%>
```

2021-09-23 21:34 UTC, mshima commented on generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> +    <%_ if (!readOnly) { _%>
```suggestion
<%_ if (!readOnly) { _%>
```

2021-09-23 21:34 UTC, mshima commented on generators/entity-client/templates/angular/src/main/webapp/app/entities/service/entity.service.spec.ts.ejs
> +    <%_ } _%>
```suggestion
<%_ } _%>
```

2021-09-23 22:31 UTC, merged