Fix no database daily builds.
jhipster/generator-jhipster pull request #17535
Opened 2022-01-10 20:00 UTC by mshima

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2022-01-10 20:18 UTC, DanielFran requested changes

2022-01-10 20:18 UTC, DanielFran commented on generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
> +   const username = Cypress.env('E2E_USERNAME') ?? '<%= skipUserManagement && (applicationTypeMonolith || applicationTypeGateway) ? 'admin' : 'user' %>';
ident

2022-01-10 20:23 UTC, mshima commented on generators/cypress/templates/src/test/javascript/cypress/integration/account/login-page.spec.ts.ejs
> +   const username = Cypress.env('E2E_USERNAME') ?? '<%= skipUserManagement && (applicationTypeMonolith || applicationTypeGateway) ? 'admin' : 'user' %>';
```suggestion
  const username = Cypress.env('E2E_USERNAME') ?? '<%= skipUserManagement && (applicationTypeMonolith || applicationTypeGateway) ? 'admin' : 'user' %>';
```

2022-01-11 01:19 UTC, DanielFran approved these changes

2022-01-11 01:19 UTC, merged