throw when different client frameworks are used for microfrontends
jhipster/generator-jhipster pull request #18470
Opened 2022-04-25 13:12 UTC by emilpaw

Fix #18200

---

Please make sure the below checklist is followed for Pull Requests.

- [x] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [x] The JDL part is updated if necessary
- [x] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2022-04-30 03:22 UTC, mshima requested changes
Should be simplified.

2022-04-30 03:22 UTC, mshima commented on cli/import-jdl.js
> +        const gatewayClientFramework = applicationWithEntities.config.clientFramework;
Move to line 434:
```
const { serverPort: gatewayServerPort, clientFramework: gatewayClientFramework } = applicationWithEntities.config;
```

2022-04-30 03:22 UTC, mshima commented on cli/import-jdl.js
> +        }
Please reuse the other loop.
Comparing clientFramework from the microservice with the gateway is enough.
No need to extract every value for the log.

2022-05-11 19:33 UTC, mshima commented on cli/import-jdl.js
> +        }
> eslint seems to not like it.

Should be forEach instead of map.

2022-05-11 21:31 UTC, emilpaw commented on cli/import-jdl.js
> +        const gatewayClientFramework = applicationWithEntities.config.clientFramework;
Done

2022-05-13 19:03 UTC, mshima requested changes
Unfortunately this won't work with main after https://github.com/jhipster/generator-jhipster/pull/18254 using new jdl microfrontend notation.
Old notation will be dropped at https://github.com/jhipster/generator-jhipster/pull/18632.
The relatedApplications needs to use microfrontends baseNames.

2022-05-13 19:03 UTC, mshima commented on cli/import-jdl.js
>            applicationWithEntities.entities.find(entity => entity.microserviceName === baseName)
Add
```js
      const microfrontends = applicationWithEntities.config.microfrontends || [];
```

```suggestion
          (
            applicationWithEntities.entities.find(entity => entity.microserviceName === baseName) ||
            microfrontends.includes(baseName)
          )
```

2022-05-15 07:40 UTC, emilpaw commented on cli/import-jdl.js
>            applicationWithEntities.entities.find(entity => entity.microserviceName === baseName)
Thanks. Done.

2022-05-21 00:31 UTC, mshima approved these changes

2022-05-21 00:32 UTC, merged

2022-12-22 15:31 UTC, emilpaw commented
Bug bounty claimed: https://opencollective.com/generator-jhipster/expenses/115032 Thanks :)

2022-12-22 17:25 UTC, DanielFran commented
@emilpaw approved