cleanup some generator methods.
jhipster/generator-jhipster pull request #20386
Opened 2022-11-17 20:17 UTC by mshima

- replace `generator.template()` with `generator.writeFile()` (matches writeFiles)
- drop `generator.render()` and `utils.renderContent()`. Use js templates instead of ejs for partial templates.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2022-11-18 13:14 UTC, mshima commented
> Please,
> I'm tired to rebase [this one](https://github.com/jhipster/generator-jhipster/pull/20286) indefinitely: its is already moving render and template in a specific folder.

Sorry about this, but I am telling for some time that we should cleanup before extracting, we will need to remove from 2 places then.

> At least, please follow the same logic instead of adding new business logic in the generator.mts file (which I'm trying hard to slim down)

New logic???
It's replacing logics with:
```ts
  writeFile(source: string, destination: string, data: TemplateData = this, options?: TemplateOptions, copyOptions?: CopyOptions) {
     // eslint-disable-next-line @typescript-eslint/no-explicit-any
     const root: any = this.jhipsterTemplatesFolders ?? this.templatePath();
     return this.renderTemplate(source, destination, data, { root, ...options }, copyOptions);
   }
```

It's just a basic default parameter chance.
`renderTemplate()`'s default data is `this._templateData()`, and adds jhipsterTemplatesFolders as root to ejs options.

There isn't any logic here.

2022-12-29 14:57 UTC, DanielFran commented
@mshima Can you fix conflicts?

2022-12-29 17:25 UTC, DanielFran requested changes

2022-12-29 17:25 UTC, DanielFran commented on generators/heroku/templates.mjs
> +    dialect = 'tech.jhipster.domain.util.FixedPostgreSQL10Dialect';
```suggestion
    dialect = 'org.hibernate.dialect.PostgreSQLDialect';
```

2022-12-29 19:58 UTC, DanielFran approved these changes

2022-12-29 20:32 UTC, merged