Fix broken Hibernate mapping of Instants
jhipster/generator-jhipster pull request #21476
Opened 2023-03-20 16:19 UTC by gzsombor

So it will be stored as UTC values inside the database, instead of Local timezone. 
This was a breaking change introduced Hibernate 6, this fix restores the previous behavior, and re-enables the test which could warn about in the future, if similar thing happens.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2023-03-20 20:00 UTC, DanielFran requested changes

2023-03-21 08:13 UTC, gzsombor commented
Unfortunately, one test fails because of 
```
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [renamed] in table [department]; found [text (Types#VARCHAR)], but expecting [oid (Types#CLOB)]
```

2023-03-21 15:39 UTC, DanielFran commented
> Unfortunately, one test fails because of
> 
> ```
> Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [renamed] in table [department]; found [text (Types#VARCHAR)], but expecting [oid (Types#CLOB)]
> ```

Is this same as this issue? https://stackoverflow.com/questions/73474448/schema-validation-wrong-column-type-encountered-in-column-name-in-table-test

2023-03-22 21:02 UTC, gzsombor commented
Unfortunately, it's not just that. After I've fixed to not use @Lob when the field is a string, we still have a bunch of other wrong column types

2023-03-23 09:41 UTC, merged

2023-03-23 09:42 UTC, DanielFran commented
Thanks @gzsombor