allow view/edit in new tabs from list view
jhipster/generator-jhipster pull request #22888
Opened 2023-07-17 14:14 UTC by nitram84

Fix #22801

It is interesting to note, that tabs were already supported by react, so there was nothing to do for react. With this PR the view and edit "buttons" for angular and vue (here only authentication type "session") work in the same way like react. Vue produces an error for links opened in new tabs when authentication type is not "session". Working with tabs works best in session mode, e.g. with JWT authentication a login for each tab is required. But even when a login is required, this PR makes it still easier to copy or share view/edit links.

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2023-08-12 08:00 UTC, deepu105 commented
Can you check the failing tests plz. Probably snapshots need to be updated using the `npm run update-snapshots` command

2023-08-14 07:05 UTC, nitram84 commented
@deepu105: The failing test cases weren’t mine. At the time I created my PR all builds had failing test cases (and those were accepted). The build of the previous PR of my PR (https://github.com/jhipster/generator-jhipster/pull/22886/checks) had the same failing test cases as my PR. So these test failures weren't caused by my PR. It seems that the failing tests are now fixed on main, so my PR shouldn't pose a problem anymore.

2023-08-17 14:22 UTC, mraible requested changes

2023-08-17 14:22 UTC, mraible commented on generators/angular/templates/src/main/webapp/app/entities/_entityFolder/list/_entityFile.component.html.ejs
> +                            <a
The formatting looks a little off after this change. Can you try moving the `[routerLink]` line up with the `<a`? Running prettier might be a good idea too.

2023-08-20 13:49 UTC, DanielFran approved these changes

2023-08-20 13:50 UTC, DanielFran commented
@nitram84 it is missing only react. Can you take a look?

2023-08-21 05:55 UTC, nitram84 commented
@DanielFran I didn't miss react. In react new tabs are supported by default for view and edit:

"It is interesting to note, that tabs were already supported by react, so there was nothing to do for react. With this PR the view and edit "buttons" for angular and vue (here only authentication type "session") work in the same way like react. [...]"

This PR reduces the differences between the supported UI libs.

For react there might be one point: React supports delete operations in new tabs, so users can copy or share a delete-link. For view and edit links this is ok - those links can be used as permalinks. This is not true for delete links, so perhaps react should use a button for delete instead of a link, if this behavior is unwanted.

2023-08-21 15:10 UTC, mraible submitted a review, later dismissed

2023-08-21 16:38 UTC, DanielFran commented
> 

@nitram84 I agree, for delete it should be a button.
Do you want to include those changes in this or?

2023-08-23 13:27 UTC, nitram84 commented
I fixed the react part too. Now all changes should be consistent.

2023-08-23 13:31 UTC, DanielFran approved these changes

2023-10-25 07:54 UTC, DanielFran commented
@nitram84 Can you fix the conflicts please?

2023-10-26 14:12 UTC, nitram84 commented
@DanielFran Thank you for reminding me. I had to rebase my changes. Rebasing worked, all changes are identical to previously reviewed commits.

2023-10-26 17:14 UTC, DanielFran approved these changes

2023-10-26 17:15 UTC, DanielFran commented
@nitram84 Can you take a look at the e2e tests, some are failing

2023-10-28 18:45 UTC, DanielFran approved these changes

2023-10-28 18:45 UTC, DanielFran commented
Thanks @nitram84 for the contribution

2023-10-28 18:45 UTC, merged

2023-11-12 15:36 UTC, mshima commented
This PR created a regression at react. See https://github.com/jhipster/generator-jhipster/issues/24115.