integrate docker compose
jhipster/generator-jhipster pull request #27062
Opened 2024-08-24 01:45 UTC by mshima

---

Please make sure the below checklist is followed for Pull Requests.

- [ ] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
- [ ] Tests are added where necessary
- [ ] The JDL part is updated if necessary
- [ ] [jhipster-online](https://github.com/jhipster/jhipster-online) is updated if necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

When you are still working on the PR, consider converting it to Draft (below reviewers) and adding `skip-ci` label, you can still see CI build result at your branch.

2024-08-27 14:55 UTC, mraible commented
Added bug bounty to the issue this fixes.

2024-09-06 19:25 UTC, mraible commented
Is there anything I can do to help move this along?

2024-09-07 14:29 UTC, mshima commented
@mraible its not clear to me how to test it.
I am thinking in adding tests to daily builds.

2024-09-07 14:39 UTC, mshima commented
I know PostgreSQL is broken due to missing password.

2024-09-07 14:41 UTC, mraible commented
We could remove the step to start Docker containers before the app starts. Maybe even remove the scripts to start containers since it'll be automatic.

2024-09-07 14:51 UTC, mshima commented
We test compiled jar for monoliths and docker images for microservices.
The compiled jar and docker image removes docker-compose lib. So it work have docker compose integration.

I think this behavior is correct because the production jar and docker images are the most important.

To test docker compose integration we should run using `./mvnw`.

2024-09-12 13:07 UTC, mshima commented on generators/spring-data-relational/support/database-data.ts
> +    defaultPassword: 'postgresql',
password is [required for databases](https://github.com/spring-projects/spring-boot/blob/ce01dbbad41496a2de6fb1c35bd08edfb8a8a430/spring-boot-project/spring-boot-docker-compose/src/test/java/org/springframework/boot/docker/compose/service/connection/mariadb/MariaDbEnvironmentTests.java#L59-L63).

2024-09-12 14:00 UTC, mshima commented
I don't get why the application does not fails in some containers failures:
```
[0] Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled. 
[0] 2024-09-12T13:21:05.843Z ERROR 3295 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed 
[0] 
[0] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
[0] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1806)
[0] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
[0] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
[0] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
[0] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
[0] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
[0] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
[0] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:954)
[0] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625)
[0] 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
[0] 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
[0] 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
[0] 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
[0] 	at com.mycompany.myapp.AppApp.main(AppApp.java:70)
[0] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[0] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[0] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[0] 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[0] 	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
[0] Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment] due to: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
[0] 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:276)
[0] 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:238)
[0] 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:215)
[0] 	at org.hibernate.boot.model.relational.Database.<init>(Database.java:45)
[0] 	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.getDatabase(InFlightMetadataCollectorImpl.java:221)
[0] 	at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:189)
[0] 	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:171)
[0] 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1431)
[0] 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1502)
[0] 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:75)
[0] 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:390)
[0] 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
[0] 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
[0] 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:366)
[0] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
[0] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1802)
[0] 	... 18 common frames omitted
[0] Caused by: org.hibernate.HibernateException: Unable to determine Dialect without JDBC metadata (please set 'jakarta.persistence.jdbc.url' for common cases or 'hibernate.dialect' when a custom Dialect implementation must be provided)
[0] 	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:191)
[0] 	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:87)
[0] 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentWithDefaults(JdbcEnvironmentInitiator.java:152)
[0] 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.getJdbcEnvironmentUsingJdbcMetadata(JdbcEnvironmentInitiator.java:362)
[0] 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:123)
[0] 	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:77)
[0] 	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:130)
[0] 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
[0] 	... 33 common frames omitted
[0] 
[0] [INFO] ------------------------------------------------------------------------
[0] [INFO] BUILD SUCCESS
[0] [INFO] ------------------------------------------------------------------------
[0] [INFO] Total time:  01:17 min
[0] [INFO] Finished at: 2024-09-12T13:21:05Z
[0] [INFO] ------------------------------------------------------------------------
```

2024-09-12 16:20 UTC, mshima commented on generators/spring-data-relational/support/database-data.ts
> +    defaultPassword: 'postgresql',
Actually is required for postgresql only.
Fixed in v3.4 branch https://github.com/spring-projects/spring-boot/pull/41511?notification_referrer_id=NT_kwDOABWf37MxMTUyMzQ1NDEzMDoxNDE3MTgz#issuecomment-2346590381

2024-09-12 20:36 UTC, mshima commented
- container integration workflow is conditional to `pr: docker-compose integration` label
- container integration workflow can have false positives
- we need to add a strong password to PostgreSQL to avoid sonar vulnerability and avoid Spring Boot issue
- MariaDB + reactive uses mysql driver, which doesn't match the url generated by the Services Connection Detail
- Cassandra is failing due to unknown issue
- if and serviceDiscovery is provided the integration fails
- keycloak is not supported

I plan to create a followup PR with improvements.

2024-09-12 20:57 UTC, mraible commented
Is there an issue detailing why Keycloak doesn't work?

2024-09-12 21:01 UTC, mshima commented
> Is there an issue detailing why Keycloak doesn't work?

https://github.com/spring-projects/spring-boot/issues/36777

2024-09-12 21:22 UTC, mshima commented on generators/spring-data-relational/support/database-data.ts
> +    defaultPassword: 'yourStrong(!)Password',
This password is reported as sonar security issue.

2024-09-12 23:03 UTC, mraible commented
When I first heard about this feature, I remember seeing it was possible to point at our existing Docker Compose files, which don't use testcontainers. Can we do that instead?

2024-09-13 01:15 UTC, mshima commented
> When I first heard about this feature, I remember seeing it was possible to point at our existing Docker Compose files, which don't use testcontainers. Can we do that instead?

It's not using testcontainers at all, so I've recently renamed the sample/workflow to docker-compose-integration.
It's using the docker-compose file.
https://github.com/mshima/generator-jhipster/blob/0ac0cf69cb35872aebb85a6e1b5a8c7d0ec209f0/generators/spring-boot/templates/src/main/resources/config/application.yml.ejs#L281.

For each docker-compose container/service there is a Spring Boot service connection that detects required data like database/user/password/port (can be random) and configure the application according to it.
I couldn't find a way to add a generic container just to start and stop without a service connection.

2024-09-13 01:46 UTC, mraible commented
The [issue you linked](https://github.com/spring-projects/spring-boot/issues/36777) to as Testcontainers in its description, that's what threw me off. The import and everything should work if it's just starting the existing Keycloak container. I can take a look.

2024-09-13 02:15 UTC, mraible commented
When I create a new app (using `jhipster jdl blog-oauth2`), it shows the package.json has changed in red. It looks like a warning when it probably doesn't matter.

<img width="1442" alt="Screenshot 2024-09-12 at 20 15 04" src="https://github.com/user-attachments/assets/449cb42c-6f5d-4153-8a9b-8dc7d6fdba14">

2024-09-13 02:16 UTC, mraible commented
It still has an eslint warning too:

```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: eslint-plugin-import@2.29.1
npm warn Found: eslint@9.9.1
npm warn node_modules/generator-jhipster/node_modules/eslint
npm warn   eslint@"9.9.1" from generator-jhipster@8.7.0
npm warn   node_modules/generator-jhipster
npm warn     dev generator-jhipster@"8.7.0" from the root project
npm warn
npm warn Could not resolve dependency:
npm warn peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm warn node_modules/generator-jhipster/node_modules/eslint-plugin-import
npm warn   eslint-plugin-import@"2.29.1" from generator-jhipster@8.7.0
npm warn   node_modules/generator-jhipster
npm warn
npm warn Conflicting peer dependency: eslint@8.57.0
npm warn node_modules/eslint
npm warn   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
npm warn   node_modules/generator-jhipster/node_modules/eslint-plugin-import
npm warn     eslint-plugin-import@"2.29.1" from generator-jhipster@8.7.0
npm warn     node_modules/generator-jhipster
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
```

2024-09-13 02:26 UTC, mraible commented
I had to enable docker in `application-dev.yml`:

```yaml
spring:
  docker:
    compose:
      enabled: true
```

Lots of logging happens at the beginning, probably unrelated to this branch.

<img width="1442" alt="Screenshot 2024-09-12 at 20 24 52" src="https://github.com/user-attachments/assets/8a3b9414-d657-49e5-8150-dd4baa7880a1">

Then, it hangs here. It might be trying to download Docker containers. If it is, I'd expect more logging.

<img width="1442" alt="Screenshot 2024-09-12 at 20 25 00" src="https://github.com/user-attachments/assets/4c73776b-f905-4693-a701-5fadb7fdb946">

2024-09-13 02:38 UTC, mraible commented
It works if I specify an absolute path to the file. It doesn't seem to work with a relative path. In `application-dev.yml`:

```yaml
spring:
  ...
  docker:
    compose:
      enabled: true
      file: /Users/mraible/Downloads/blog/src/main/docker/services.yml
```

2024-09-13 02:39 UTC, mshima commented
> It still has an eslint warning too:
> 
> ```
> npm warn ERESOLVE overriding peer dependency
> npm warn While resolving: eslint-plugin-import@2.29.1
> npm warn Found: eslint@9.9.1
> npm warn node_modules/generator-jhipster/node_modules/eslint
> npm warn   eslint@"9.9.1" from generator-jhipster@8.7.0
> npm warn   node_modules/generator-jhipster
> npm warn     dev generator-jhipster@"8.7.0" from the root project
> npm warn
> npm warn Could not resolve dependency:
> npm warn peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
> npm warn node_modules/generator-jhipster/node_modules/eslint-plugin-import
> npm warn   eslint-plugin-import@"2.29.1" from generator-jhipster@8.7.0
> npm warn   node_modules/generator-jhipster
> npm warn
> npm warn Conflicting peer dependency: eslint@8.57.0
> npm warn node_modules/eslint
> npm warn   peer eslint@"^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8" from eslint-plugin-import@2.29.1
> npm warn   node_modules/generator-jhipster/node_modules/eslint-plugin-import
> npm warn     eslint-plugin-import@"2.29.1" from generator-jhipster@8.7.0
> npm warn     node_modules/generator-jhipster
> npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
> ```

v8.7.0 release is installed.

2024-09-13 02:40 UTC, mraible commented
This works:

```yaml
  docker:
    compose:
      enabled: true
      file: src/main/docker/services.yml
```

2024-09-13 02:42 UTC, mshima commented
> Lots of logging happens at the beginning, probably unrelated to this branch.

Fixed in https://github.com/jhipster/generator-jhipster/pull/27267

2024-09-13 02:51 UTC, mraible commented
> v8.7.0 release is installed.

I don't think so. I'm pulling from your `compose` branch, running `npm ci` and `npm link` before I run `jhipster`. I tried just now with `npm uninstall -g generator-jhipster` first to prove it's a local install and it has the same behavior.

2024-09-13 02:55 UTC, mraible commented
I added the following to `logback-spring.xml` to see the downloading images progress.

```xml
<logger name="org.springframework.boot.docker" level="INFO"/>
```

<img width="1442" alt="Screenshot 2024-09-12 at 20 54 24" src="https://github.com/user-attachments/assets/13f3ce87-f6e8-4844-8c2c-f202c86dfa28">

2024-09-13 03:01 UTC, mraible commented
This might help: https://github.com/mshima/generator-jhipster/pull/1010

2024-09-13 09:53 UTC, mshima commented
> This might help: [mshima#1010](https://github.com/mshima/generator-jhipster/pull/1010)

@mraible that config is already provided in application.yml

2024-09-13 10:45 UTC, mshima commented
> > v8.7.0 release is installed.
> 
> I don't think so. I'm pulling from your `compose` branch, running `npm ci` and `npm link` before I run `jhipster`. I tried just now with `npm uninstall -g generator-jhipster` first to prove it's a local install and it has the same behavior.

Unless --skip-jhipster-dependencies is used, latest release will be installed.

2024-09-13 13:14 UTC, mraible commented
> that config is already provided in application.yml

Shouldn't it only be in dev since it's only needed when using the dev profile?

2024-09-13 14:04 UTC, mraible commented
> Unless --skip-jhipster-dependencies is used, latest release will be installed.

That's right. Sorry, I forgot about this after not working on the project for the last month. If I use this argument, the app is generated w/o the eslint warnings and starts with `./mvnw` as expected. It also fails with `mvn -Pprod`, which is expected. I also tried starting the containers with `docker compose -f src/main/docker/services.yml up` and starting with `mvn`. This works too, proving it should be backward compatible.

2024-09-13 14:15 UTC, mshima commented
> > that config is already provided in application.yml
> 
> Shouldn't it be in application-dev.yml since it's only needed when using the dev profile?

It should work using prod profile for maven passing:
`./mvnw -Pprod,docker-compose`

For gradle it should work without docker-compose profile.

`docker-compose` dependency is in a profile due to https://github.com/GoogleContainerTools/jib-extensions/issues/158.

2024-09-13 14:30 UTC, mraible commented
I tried to see if it's working with microservices. It appears there might be issues.

I generated microservices using `jhipster jdl reactive-mf --skip-jhipster-dependencies`. Then, I navigated into the gateway directory and ran `./gradlew`. I get an error:

```
java.lang.IllegalStateException: No Docker Compose file found in directory '/Users/mraible/Downloads/microfrontends/gateway/.'
```

The settings appear to be the same, so not sure why this is happening.

```
$ cat src/main/resources/config/application.yml | grep docker
  docker:
      file: src/main/docker/services.yml
```

Maybe this has something to do with setting the working directory in Gradle? https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/150

I don't see the problem if I re-generate the `blog-oauth2` monolith with Gradle.

2024-09-13 14:49 UTC, mshima commented
@mraible see 2 latest commits for service discovery.
But seems to have a dependency problem now.

2024-09-13 15:53 UTC, DanielFran requested changes

2024-09-13 15:53 UTC, DanielFran commented on generators/common/__snapshots__/generator.spec.ts.snap
>    S1192,S125,S3437,S4502,S4684,S5145,UndocumentedApi
```suggestion
  S1192,S125,S3437,S4502,S4684,S5145,S6437,UndocumentedApi
```

2024-09-13 15:53 UTC, mraible commented
I tried generating microservices again with the latest code and the gateway seems to hang on startup.

<img width="1442" alt="Screenshot 2024-09-13 at 09 43 48" src="https://github.com/user-attachments/assets/e2209827-a15a-495b-95fc-c9e286345ae2">

It eventually starts, but there's no logging about downloading containers. 

<img width="1442" alt="Screenshot 2024-09-13 at 09 45 02" src="https://github.com/user-attachments/assets/29712781-a0d6-48ea-984c-d69b410c5301">

If I try to start the "blog" microservice, it fails with the following error:

```
 Container blog-neo4j-1  Started
 Container blog-consul-config-loader-1  Started
Error response from daemon: driver failed programming external connectivity on endpoint blog-consul-1 (df4e3264b57f8306e3a92cc7ad5701ceb8ce9bdda8a1fcdb0a80216371b3c2c9): Bind for 127.0.0.1:8300 failed: port is already allocated

        at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:96)
        at org.springframework.boot.docker.compose.core.DockerCli.run(DockerCli.java:80)
```

If I start the "store" microservice, the error is similar:

```
 Container store-consul-1  Starting
 Container store-consul-config-loader-1  Started
 Container store-mongodb-1  Started
Error response from daemon: driver failed programming external connectivity on endpoint store-keycloak-1 (0a8311dbce4c3f30e4ce5bbcd93400a17ce70c74ec7c6bec77efb2b0385b95e9): Bind for 127.0.0.1:9080 failed: port is already allocated

        at org.springframework.boot.docker.compose.core.ProcessRunner.run(ProcessRunner.java:96)
        at org.springframework.boot.docker.compose.core.DockerCli.run(DockerCli.java:80)
```

`docker ps` shows the following:

```
CONTAINER ID   IMAGE                                  COMMAND                  CREATED         STATUS                   PORTS                                                                                                        NAMES
42f3b4cec5ca   jhipster/consul-config-loader:v0.4.1   "/bin/sh -c /load-co…"   4 minutes ago   Up 4 minutes                                                                                                                          blog-consul-config-loader-1
c0d9b8482ed1   neo4j:5.23.0                           "tini -g -- /startup…"   4 minutes ago   Up 4 minutes (healthy)   127.0.0.1:7474->7474/tcp, 7473/tcp, 127.0.0.1:7687->7687/tcp                                                 blog-neo4j-1
66d3ccc65525   jhipster/consul-config-loader:v0.4.1   "/bin/sh -c /load-co…"   4 minutes ago   Up 4 minutes                                                                                                                          store-consul-config-loader-1
b8e596c9ea9f   mongo:7.0.6                            "docker-entrypoint.s…"   4 minutes ago   Up 4 minutes (healthy)   127.0.0.1:27017->27017/tcp                                                                                   store-mongodb-1
3f252b934acc   quay.io/keycloak/keycloak:25.0.1       "/opt/keycloak/bin/k…"   8 minutes ago   Up 8 minutes (healthy)   8080/tcp, 8443/tcp, 127.0.0.1:9080->9080/tcp, 9000/tcp, 127.0.0.1:9443->9443/tcp                             gateway-keycloak-1
e61812c3c2b3   postgres:16.4                          "docker-entrypoint.s…"   8 minutes ago   Up 8 minutes (healthy)   127.0.0.1:5432->5432/tcp                                                                                     gateway-postgresql-1
cffdb1ad1c97   bitnami/consul:1.19.2                  "/opt/bitnami/script…"   8 minutes ago   Up 8 minutes             127.0.0.1:8300->8300/tcp, 8301/udp, 127.0.0.1:8500->8500/tcp, 127.0.0.1:8600->8600/tcp, 8301/tcp, 8600/udp   gateway-consul-1
c4eb3697180d   jhipster/consul-config-loader:v0.4.1   "/bin/sh -c /load-co…"   8 minutes ago   Up 8 minutes                                                                                                                          gateway-consul-config-loader-1
```

I suspected this might happen, that's why I QA'd it. I believe we might have to remove some Docker Compose files from microservices because they'll already be started by the gateway.

2024-09-13 15:56 UTC, DanielFran requested changes

2024-09-13 15:56 UTC, DanielFran commented on generators/common/templates/sonar-project.properties.ejs
>    S4684,S5145,UndocumentedApi
```suggestion
  S4684,S5145, \
<%_ if (backendTypeSpringBoot) { _%>
  S6437,\
<%_ } _%>
  UndocumentedApi
```

2024-09-13 15:58 UTC, mshima commented
> It eventually starts, but there's no logging about downloading containers.

I’ve reduced the log to warn, it’s too verbose in CI.

2024-09-13 19:34 UTC, DanielFran approved these changes

2024-09-13 19:55 UTC, mshima commented
> I suspected this might happen, that's why I QA'd it. I believe we might have to remove some Docker Compose files from microservices because they'll already be started by the gateway.

microservices now depends on the database compose file instead of services.

2024-09-14 10:10 UTC, DanielFran approved these changes

2024-09-14 14:33 UTC, mraible commented
I tested again with microservices and confirmed everything starts and works as expected. Nice work, @mshima!

2024-09-14 14:33 UTC, mraible approved these changes

2024-09-14 14:33 UTC, merged